### ISSUE TITLE
jdraw_view in PyQt5 does not work with Tango JD names

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#1006]
This issue was observed while fixing https://github.com/taurus-org/taurus/issues/1004.

Consider the following foo.jdw file:

```
JDFile v11 {
  Global {
  }
  JDRectangle {
    summit:0,10,0,10
    origin:0,0
    lineWidth:3
    name:"sys/tg_test/1"
  }
}
```

which raises the following exception:

```console
zreszela@pc255:~/workspace/taurus (fix-1004)> QT_API=pyqt5 python3 -m taurus.qt.qtgui.graphic.jdraw.jdraw_view ../foo.jdw
MainThread     INFO     2019-09-18 17:47:37,580 TaurusRootLogger: Using PyQt5 (v5.7 with Qt 5.7.1 and Python 3.5.3)
MainThread     INFO     2019-09-18 17:47:38,290 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/icon/)
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
MainThread     INFO     2019-09-18 17:47:39,511 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
/usr/lib/python3.5/runpy.py:125: RuntimeWarning: 'taurus.qt.qtgui.graphic.jdraw.jdraw_view' found in sys.modules after import of package 'taurus.qt.qtgui.graphic.jdraw', but prior to execution of 'taurus.qt.qtgui.graphic.jdraw.jdraw_view'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
MainThread     WARNING  2019-09-18 17:47:40,507 TaurusRootLogger: if you use a tango name as JD name it must with tango:
MainThread     WARNING  2019-09-18 17:47:40,510 TaurusJDrawGraphicsFactory: Error fetching object
MainThread     INFO     2019-09-18 17:47:40,510 TaurusJDrawGraphicsFactory: Details:
Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 135, in getObj
    obj = method(params)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 145, in getRectangleObj
    item = self.getGraphicsItem('Rectangle', params)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1562, in getGraphicsItem
    item = klass()
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1267, in __init__
    Qt.QGraphicsRectItem.__init__(self, parent, scene)
TypeError: arguments did not match any overloaded call:
  QGraphicsRectItem(parent: QGraphicsItem = None): too many arguments
  QGraphicsRectItem(QRectF, parent: QGraphicsItem = None): argument 1 has unexpected type 'NoneType'
  QGraphicsRectItem(float, float, float, float, parent: QGraphicsItem = None): argument 1 has unexpected type 'NoneType'
MainThread     WARNING  2019-09-18 17:47:40,512 JDraw Parser: Failed to parse /home/zreszela/workspace/foo.jdw
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_view.py", line 496, in <module>
    jdraw_view_main()
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_view.py", line 491, in jdraw_view_main
    form.setModel(sys.argv[1])
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_view.py", line 392, in setModel
    scene.setSelectionStyle(self._selectionStyle)
AttributeError: 'NoneType' object has no attribute 'setSelectionStyle'
```

**Comment by cpascual** [comment]
I cannot reproduce this anymore. I think that #1029 fixed it.
