### ISSUE TITLE
taurus tpg plot does not wokrk with pyqt4

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#1009]
```
zreszela@pc255:~/workspace/sardana (channel_widget)> taurus tpg plot --demo
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
MainThread     WARNING  2019-09-23 12:34:45,690 TaurusRootLogger: <frozen importlib._bootstrap>:222: DeprecationWarning: taurus.external.qt.Qwt5 is deprecated since 4.5

Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus_pyqtgraph/taurus_pyqtgraph/plot.py", line 129, in __getattr__
    return PlotWidget.__getattr__(self, item)
  File "/usr/lib/python3/dist-packages/pyqtgraph/widgets/PlotWidget.py", line 79, in __getattr__
    raise NameError(attr)
NameError: _BaseConfigurableClass__configurableItemNames

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zreszela/.local/bin/taurus", line 11, in <module>
    load_entry_point('taurus', 'console_scripts', 'taurus')()
  File "/home/zreszela/workspace/taurus/lib/taurus/cli/cli.py", line 112, in main
    taurus_cmd()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/zreszela/workspace/taurus_pyqtgraph/taurus_pyqtgraph/cli.py", line 61, in plot_cmd
    window_name=window_name
  File "/home/zreszela/workspace/taurus_pyqtgraph/taurus_pyqtgraph/plot.py", line 249, in plot_main
    w = TaurusPlot()
  File "/home/zreszela/workspace/taurus_pyqtgraph/taurus_pyqtgraph/plot.py", line 94, in __init__
    self.restoreState, 'state')
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtcore/configuration/configuration.py", line 307, in registerConfigProperty
    return self._registerConfigurableItem(p, name=name)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtcore/configuration/configuration.py", line 335, in _registerConfigurableItem
    if name in self.__configurableItemNames:
  File "/home/zreszela/workspace/taurus_pyqtgraph/taurus_pyqtgraph/plot.py", line 132, in __getattr__
    self.__class__.__name__, item)
AttributeError: TaurusPlot has no attribute _BaseConfigurableClass__configurableItemNames
```

With pyqt5 it works fine:
```
zreszela@pc255:~/workspace/sardana (channel_widget)> QT_API=pyqt5 taurus tpg plot --demo   
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
MainThread     INFO     2019-09-23 12:35:04,653 TaurusRootLogger: 
*********************
< Deprecation Counts (0):
 >
```

**Comment by cpascual** [comment]
Fixed with https://github.com/taurus-org/taurus_pyqtgraph/commit/64f0239ab97c27db32d07a77b61f7798110b1152
