### ISSUE TITLE
Openining a taurus gui with Taurus+Python3+debian9

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#1015]
I get the following message in the console when executing:
taurus gui tgconf_bl09

```
MainThread     ERROR    2019-10-02 13:24:35,031 TaurusGui: Cannot add applet monitor
MainThread     INFO     2019-10-02 13:24:35,033 TaurusGui: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/taurus/qt/qtgui/taurusgui/taurusgui.py", line 1388, in _loadCustomApplets
    w = d.getWidget(sdm=Qt.qApp.SDM, setModel=False)
  File "/usr/lib/python3/dist-packages/taurus/qt/qtgui/taurusgui/utils.py", line 214, in getWidget
    klass = TaurusWidgetFactory().getWidgetClass(self.classname)
  File "/usr/lib/python3/dist-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py", line 207, in getWidgetClass
    return self._qt_widgets[name][1]
KeyError: 'TaurusMonitorTiny'


        ------------------------------------------------------------
         filename = /usr/lib/python3/dist-packages/taurus/qt/qtgui/taurusgui/taurusgui.py
         function = _loadCustomApplets
             line = [1387]: pass
          -> line = [1388]: w = d.getWidget(sdm=Qt.qApp.SDM, setModel=False)
             line = [1389]: if d.model is not None:
           locals = 
                                   d = <taurus.qt.qtgui.taurusgui.utils.AppletDescription object at 0x7f413c0322e8>
                      custom_applets = [<taurus.qt.qtgui.taurusgui.utils.AppletDescription object at 0x7f413c0322e8>]
                 applet_descriptions = None
                             MONITOR = ['pc/machinepc_ctrl/1/Value']
                                   e = 'TaurusMonitorTiny'
                             xmlroot = <Element taurusgui_config at 0x7f411035a608>
                                conf = <module 'tgconf_bl09' from 'tgconf_bl09/__init__.py'>
                                self = <taurus.qt.qtgui.taurusgui.taurusgui.TaurusGui object at 0x7f41319c24c8>
                                 msg = Cannot add applet monitor
        ------------------------------------------------------------
         filename = /usr/lib/python3/dist-packages/taurus/qt/qtgui/taurusgui/utils.py
         function = getWidget
             line = [213]: if self.modulename is None:
          -> line = [214]: klass = TaurusWidgetFactory().getWidgetClass(self.classname)
             line = [215]: w = klass()
           locals = 
                                self = <taurus.qt.qtgui.taurusgui.utils.AppletDescription object at 0x7f413c0322e8>
                            setModel = False
                                 sdm = <taurus.qt.qtcore.communication.communication.SharedDataManager object at 0x7f41[...]
        ------------------------------------------------------------
         filename = /usr/lib/python3/dist-packages/taurus/qt/qtgui/util/tauruswidgetfactory.py
         function = getWidgetClass
             line = [206]: def getWidgetClass(self, name):
          -> line = [207]: return self._qt_widgets[name][1]
             line = [208]: 
           locals = 
                                self = <taurus.qt.qtgui.util.tauruswidgetfactory.TaurusWidgetFactory object at 0x7f413c[...]
                                name = TaurusMonitorTiny

```

**Comment by cpascual** [comment]
Hi. `TaurusMonitorTiny` is a a widget provided by the `taurus.qt.qtgui.qwt5` module, which is not implemented in `taurus-pyqtgraph`.

We should at least provide a dummy implementation to avoid exceptions in existing GUIs, and we could also consider to implement a functional replacement based on pyqtgraph.

**Comment by mrosanes** [comment]
Thus, we can leave this issue opened and use it as a feature request for creating a new TaurusMonitor:

- Provide a dummy implementation to avoid exceptions in existing GUIs
- Implement a functional replacement based on pyqtgraph.
