### ISSUE TITLE
sardana/taurus issue Taurus4+Debian9+Python3: JSON econding issue

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#1016]
JSON econding issue.

Appeared when trying to launch ctbl09 in debian pcbl0906, while performing a scan in BL09 from pcbl0905:

```
-- Description -----------------------------------------------------------------
An error occured in 'ctbl09 ' on Wed Oct  2 17:28:46 2019
TypeError: the JSON object must be str, not 'bytes'


-- Details ---------------------------------------------------------------------
TypeError: the JSON object must be str, not 'bytes'

-- Origin ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/taurus/core/util/event.py", line 141, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/taurus/core/tango/tangoattribute.py", line 820, in push_event
    self.fireEvent(etype, evalue, listeners=listeners)
  File "/usr/lib/python3/dist-packages/taurus/core/taurusmodel.py", line 294, in fireEvent
    l(self, event_type, event_value)
  File "/usr/lib/python3/dist-packages/sardana/taurus/qt/qtcore/tango/sardana/macroserver.py", line 79, in recordDataReceived
    res = BaseDoor.recordDataReceived(self, s, t, v)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 657, in recordDataReceived
    return self._processRecordData(v)
  File "/usr/lib/python3/dist-packages/sardana/taurus/core/tango/sardana/macroserver.py", line 669, in _processRecordData
    data = codec.decode(data)
  File "/usr/lib/python3/dist-packages/taurus/core/util/codecs.py", line 355, in decode
    data = json.loads(data[1])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
--------------------------------------------------------------------------------
```

**Comment by cpascual** [comment]
Can you provide a way of reproducing?

Notes:
- this may be a bug in sardana, not taurus
- this may be related with mixing an old sardana server with a new sardana client

**Comment by cpascual** [comment]
Is this still an issue, or can we close it?
