### ISSUE TITLE
Qt.QGraphicsItem do not provide a constructor with scene

### ISSUE THREAD

**Issue by vallsv** [taurus-org/taurus#1025]
Hi,

The module `taurus/qt/qtgui/graphic/taurusgraphic.py` tries to construct a lot of `QGraphicsItem` using `scene` in the constructor. It looks like it is not part of the API for Qt4.8 or Qt5.

I guess items have to be added using `scene.addItem(item)` but it's maybe not obvious.

```
Traceback (most recent call last):
  File "/bliss/users/valls/miniconda3/envs/id16env2/lib/python2.7/site-packages/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 135, in getObj
    obj = method(params)
  File "/bliss/users/valls/miniconda3/envs/id16env2/lib/python2.7/site-packages/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 185, in getPolylineObj
    item = self.getGraphicsItem('Polyline', params)
  File "/bliss/users/valls/miniconda3/envs/id16env2/lib/python2.7/site-packages/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1535, in getGraphicsItem
    item = klass()
  File "/bliss/users/valls/miniconda3/envs/id16env2/lib/python2.7/site-packages/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1353, in __init__
    Qt.QGraphicsPolygonItem.__init__(self, parent, scene)
```

I could try to use Taurus master tomorrow and create a patch if you like.

**Comment by cpascual** [comment]
Hi, thanks for reporting.
Can you please provide instructions (or a snippet) on how to reproduce it?

**Comment by vallsv** [comment]
I found jdw files on your repo.

You can try to open `doc/source/devel/examples/dumpy-bakeout.jdw`

```
w = TaurusJDrawSynopticsView()
w.setModel(jdraw_path)
```


```
Traceback (most recent call last):
  File "/mntdirect/_bliss/users/valls/workspace/taurus.git/lib/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 135, in getObj
    obj = method(params)
  File "/mntdirect/_bliss/users/valls/workspace/taurus.git/lib/taurus/qt/qtgui/graphic/jdraw/jdraw.py", line 254, in getGroupObj
    item = self.getGraphicsItem('Group', params)
  File "/mntdirect/_bliss/users/valls/workspace/taurus.git/lib/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1562, in getGraphicsItem
    item = klass()
  File "/mntdirect/_bliss/users/valls/workspace/taurus.git/lib/taurus/qt/qtgui/graphic/taurusgraphic.py", line 1344, in __init__
    Qt.QGraphicsItemGroup.__init__(self, parent, scene)
TypeError: QGraphicsItemGroup(parent: QGraphicsItem = None): too many arguments
```

**Comment by vallsv** [comment]
And here is the last doc from Qt using this API: https://qt.developpez.com/doc/4.2/qgraphicsitem/#qgraphicsitem

**Comment by vallsv** [comment]
I have something launchable on my side. This commit looks to be enough 17acac683a4892aef9f21cac542887ce0a24fc81 if you like. I will continue to check and fix stuffs on this branch until i have something stable.

I have a problem with the file `doc/source/devel/examples/dumpy-bakeout.jdw` but i think it was not working anyway on the past. I check Taurus 3.5.0, and i think there was nothing about `JDBar`, Then it is another problem, but not a regression.

**Comment by cpascual** [comment]
Hi @vallsv , since you are already fixing, please make a PR so that we can review and comment on the changes

**Comment by vallsv** [comment]
Here you have #1029
