### ISSUE TITLE
PMTV in compact mode raises expception on Taurus GUI start

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#1071]
To reproduce:
1. Create taurus newgui
2. Add a TaurusForm panel to the GUI and set a motor as the model
3. Change PMTV to compact mode
4. Close the GUI
5. Open the GUI

Then you get:

```
Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 394, in filterEvent
    self.handleEvent(*evt)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/input/tauruslineedit.py", line 151, in handleEvent
    self._updateValidator(evt_value)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/input/tauruslineedit.py", line 98, in _updateValidator
    bottom, top = attr.range
AttributeError: 'NoneType' object has no attribute 'range'
```

**Comment by reszelaz** [comment]
Sorry, I wanted to report it in Sardana.

**Comment by cmft** [comment]
Hi @reszelaz ,
 IMO the issue is in taurus so I reopen it. I did a PR to fix it

**Comment by reszelaz** [comment]
Sure, then I'm closing the one from Sardana. Thanks!
