### ISSUE TITLE
Quantity magnitude cannot be an empty string

### ISSUE THREAD

**Issue by vallsv** [taurus-org/taurus#1150]
Hi,

Here is a log i have noticed in my beamline.

For now i have no idea where is come from.
I suspect it is because i was using `fgRole=rvalue.magnitude`. But i am not sure. Maybe with a non running device.
I can provide more information next week.

```
MainThread     ERROR    2020-09-10 10:47:58 root: Quantity magnitude cannot be an empty string.
Traceback (most recent call last):
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/taurus/qt/qtgui/base/taurusbase.py", line 425, in filterEvent
    self.handleEvent(*evt)
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/taurus/qt/qtgui/display/tauruslabel.py", line 316, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/taurus/qt/qtgui/base/tauruscontroller.py", line 122, in handleEvent
    self.update()
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/taurus/qt/qtgui/base/tauruscontroller.py", line 139, in update
    self._updateForeground(widget)
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/taurus/qt/qtgui/display/tauruslabel.py", line 99, in _updateForeground
    self._text = text = label.prefixText + value + label.suffixText
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/pint/quantity.py", line 754, in __add__
    return self._add_sub(other, operator.add)
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/pint/quantity.py", line 75, in wrapped
    result = f(self, *args, **kwargs)
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/pint/quantity.py", line 663, in _add_sub
    _to_magnitude(other, self.force_ndarray))
  File "/users/blissadm/conda/miniconda/envs/linecontrol/lib/python2.7/site-packages/pint/compat/__init__.py", line 81, in _to_magnitude
    raise ValueError('Quantity magnitude cannot be an empty string.')
ValueError: Quantity magnitude cannot be an empty string.
```

**Comment by cpascual** [comment]
Thanks @vallsv !
Without more context I don't know where it comes from. If you can find a way of reproducing it, it would be great.

**Comment by vallsv** [comment]
It's not obvious from the backtrace, but the widget was a custom one from my side. 
I still have to investigate, but i think the bug is not part of Taurus.
I close this issue.
