### ISSUE TITLE
appveyor build fails due to problematic version string

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#352]
The problem seems to be when building the msi.

See https://ci.appveyor.com/project/taurusorg/taurus/build/1.0.4

```
python setup.py bdist_wheel bdist_msi
(...)
C:\projects\taurus\venv_build\lib\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '4.0.2-dev' to '4.0.2.dev0'
  normalized_version,
Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    test_suite='taurus.test.testsuite.get_taurus_suite',
  File "c:\python27-x64\Lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\python27-x64\Lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\python27-x64\Lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\python27-x64\Lib\distutils\command\bdist_msi.py", line 236, in run
    sversion = "%d.%d.%d" % StrictVersion(version).version
  File "c:\python27-x64\Lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "c:\python27-x64\Lib\distutils\version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '4.0.2.dev0'
```

**Comment by cpascual** [comment]
Note: as a temporary workaround, we could restrict the msi creation to tags, or to commits on master
