### ISSUE TITLE
TaurusDevicePanel

### ISSUE THREAD

**Issue by NexeyaSGara** [taurus-org/taurus#361]
On windows Machine with Taurus 4.0.1

I'm trying to launch a taurusdevicepanel on a ds_LimaDetector device (but also with ohter devices).
For read attributes of double type, I'm getting a warning "Using default display widget" but there isn't anything in the created label neither a label with the name. With all others attributes it's ok.

**Comment by cpascual** [comment]
Does it only happen with read-only attributes?

Can you please report what happens when you do, e.g.,:
~~~
taurusform sys/tg_test/1/double_scalar
~~~

Also, can you please report what you get when you run taurusdevicepanel with `--taurus-log-level=trace`?

**Comment by NexeyaSGara** [comment]
Hi,

`taurusform sys/tg_test/1/double_scalar`

This one is works as expected but 

`taurusform sys/tg_test/1/double_scalar_ro `

this one triggers the problem

**Comment by cpascual** [comment]
I just tested with taurus 4.0.1 and with 4.0.3-alpha (both on linux), using a read-only double attribute (I used a PyAttributeProcessor DS with a dynamic attribute defined as `x=double(5)`) and it worked for me (I tried on linux, though)

**Comment by NexeyaSGara** [comment]
I'm getting the same exception when trying from the TangoBox9, but it's with taurus 3.6: 

![image](https://cloud.githubusercontent.com/assets/2578703/21850875/ff07093c-d80c-11e6-9467-993404ec82ab.png)

`MainThread     WARNING  2017-01-11 14:42:42,681 TaurusForm: Cannot handle model "tango://eu-000841:20000/tango/test/temp/temperature". Using default widget.`

**Comment by cpascual** [comment]
> Tangotest doesn't have a read-only double_scalar...

ok, let's use the following DS for the tests:

https://gist.github.com/cpascual/00bca45ee093874261e2dcbbef01db0b

Download it (as a file called `TangoSchemeTest`) and register it in your database by running the following in ipython:

```
import tango
dev_info = tango.DbDevInfo()
dev_info.server = "TangoSchemeTest/test"
dev_info._class = "TangoSchemeTest"
dev_info.name = "test/TangoSchemeTest/1"
db = tango.Database()
db.add_device(dev_info)
```

Now run the DS in a console with:

```
~$ python TangoSchemeTest test
Ready to accept request
```

And in another console, try to show the double_scalar_ro attribute:

```
~$ taurusform test/TangoSchemeTest/1/double_scalar_ro
```

You shoud get something like: 


![screenshot_20170111_195310](https://cloud.githubusercontent.com/assets/4115224/21861979/99242188-d837-11e6-8d9e-8a3e822b459a.png)

**Comment by NexeyaSGara** [comment]
Hi, 
With your DS, I get the same as expected.
With one of my DS, I think it was the unit that messed up "°C".
But with ds_LimaDetector (cpp version of LimaCDDs.py) I'm getting a blanck label for a certain number of attributes.

![image](https://cloud.githubusercontent.com/assets/2578703/21884731/ca6c09a4-d8b4-11e6-9c97-0d4ec48d286c.png)


Here is what happend to each "non working" attribute 
```

MainThread     DEBUG    2017-01-12 10:50:13,582 TaurusValue: Exception occured while trying to attach 'lima/test/test/detectorHeightMax'
MainThread     TRACE    2017-01-12 10:50:13,726 TaurusValue: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\base\taurusbase.py", line 774, in _attach
    self.modelObj = taurus.Manager().getObject(cls, self.modelName)
  File "C:\Python27\lib\site-packages\taurus\core\taurusmanager.py", line 203, in getObject
    return factory.getObject(cls, name)
  File "C:\Python27\lib\site-packages\taurus\core\taurusfactory.py", line 233, in getObject
    return self.getAttribute(name)
  File "C:\Python27\lib\site-packages\taurus\core\tango\tangofactory.py", line 369, in getAttribute
    attr = attr_klass(full_attr_name, dev, **kwargs)
  File "C:\Python27\lib\site-packages\taurus\core\tango\tangoattribute.py", line 292, in __init__
    self._decodeAttrInfoEx(attr_info)
  File "C:\Python27\lib\site-packages\taurus\core\tango\tangoattribute.py", line 867, in _decodeAttrInfoEx
    units = unit_from_tango(i.unit)
  File "C:\Python27\lib\site-packages\taurus\core\tango\util\tango_taurus.py", line 120, in unit_from_tango
    return UR.parse_units(unit)
  File "C:\Python27\lib\site-packages\taurus\external\pint\pint_local\unit.py", line 1138, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "C:\Python27\lib\site-packages\taurus\external\pint\pint_local\unit.py", line 1153, in _parse_units
    units = ParserHelper.from_string(input_string)
  File "C:\Python27\lib\site-packages\taurus\external\pint\pint_local\util.py", line 405, in from_string
    return cls._from_string(input_string)
  File "C:\Python27\lib\site-packages\taurus\external\pint\pint_local\compat\lrucache.py", line 129, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python27\lib\site-packages\taurus\external\pint\pint_local\util.py", line 439, in _from_string
    ret = build_eval_tree(gen).evaluate(cls.eval_token)
AttributeError: 'NoneType' object has no attribute 'evaluate'


        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\qt\qtgui\base\taurusbase.py
         function = _attach
             line = [773]: try:
          -> line = [774]: self.modelObj = taurus.Manager().getObject(cls, self.modelName)
             line = [775]: if self.modelObj is not None:
           locals =
                                self = <taurus.qt.qtgui.panel.taurusvalue.TaurusValue object at 0x0659F0C0>
                                 cls = <class 'taurus.core.tango.tangoattribute.TangoAttribute'>
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\taurusmanager.py
         function = getObject
             line = [202]: return
          -> line = [203]: return factory.getObject(cls, name)
             line = [204]:
           locals =
                                self = TaurusManager()
                                 cls = <class 'taurus.core.tango.tangoattribute.TangoAttribute'>
                             factory = TangoFactory()
                                name = lima/test/test/detectorHeightMax
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\taurusfactory.py
         function = getObject
             line = [232]: elif issubclass(cls, TaurusAttribute):
          -> line = [233]: return self.getAttribute(name)
             line = [234]: # For backward compatibility
           locals =
                              t4_msg = The TaurusConfiguration classes are deprecated in tep14
                                self = TangoFactory()
                                name = lima/test/test/detectorHeightMax
                                 cls = <class 'taurus.core.tango.tangoattribute.TangoAttribute'>
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\tango\tangofactory.py
         function = getAttribute
             line = [368]: 'pollingPeriod'] = self.getDefaultPollingPeriod()
          -> line = [369]: attr = attr_klass(full_attr_name, dev, **kwargs)
             line = [370]: # attribute objects will register themselves in this factory
           locals =
                    create_if_needed = True
                          attr_klass = <class 'taurus.core.tango.tangoattribute.TangoAttribute'>
                                self = TangoFactory()
                           attr_name = lima/test/test/detectorHeightMax
                                 dev = TangoDevice(lima/test/test)
                            dev_name = tango://eu-000841:20000/lima/test/test
                           validator = <taurus.core.tango.tangovalidator.TangoAttributeNameValidator object at 0x061A9E[...]
                              groups = {'_shortattrname': 'detectorHeightMax', 'fragment': None, '_devalias': None, 'de[...]
                              kwargs = {'storeCallback': <bound method TangoFactory._storeAttribute of TangoFactory(sch[...]
                      full_attr_name = tango://eu-000841:20000/lima/test/test/detectorHeightMax
                                   _ = detectorHeightMax
                                attr = None
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\tango\tangoattribute.py
         function = __init__
             line = [291]: self._pytango_attrinfoex = None
          -> line = [292]: self._decodeAttrInfoEx(attr_info)
             line = [293]:
           locals =
                           attr_info = AttributeInfoEx[[...]
                                name = tango://eu-000841:20000/lima/test/test/detectorHeightMax
                              parent = TangoDevice(lima/test/test)
                                self = tango://eu-000841:20000/lima/test/test/detectorHeightMax
                           attr_name = detectorHeightMax
                              kwargs = {'storeCallback': <bound method TangoFactory._storeAttribute of TangoFactory(sch[...]
                           dis_level = OPERATOR
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\tango\tangoattribute.py
         function = _decodeAttrInfoEx
             line = [866]: # quantities if appropriate
          -> line = [867]: units = unit_from_tango(i.unit)
             line = [868]: if PyTango.is_numerical_type(i.data_type, inc_array=True):
           locals =
                                   i = AttributeInfoEx[[...]
                                self = tango://eu-000841:20000/lima/test/test/detectorHeightMax
                  pytango_attrinfoex = AttributeInfoEx[[...]
                                desc =
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\core\tango\util\tango_taurus.py
         function = unit_from_tango
             line = [119]: try:
          -> line = [120]: return UR.parse_units(unit)
             line = [121]: except UndefinedUnitError:
           locals =
                                unit =
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\external\pint\pint_local\unit.py
         function = parse_units
             line = [1137]: """
          -> line = [1138]: units = self._parse_units(input_string, as_delta)
             line = [1139]: return self.Unit(units)
           locals =
                        input_string =
                                self = <taurus.external.pint.pint_local.unit.UnitRegistry object at 0x0548D5F0>
                            as_delta = None
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\external\pint\pint_local\unit.py
         function = _parse_units
             line = [1152]:
          -> line = [1153]: units = ParserHelper.from_string(input_string)
             line = [1154]: if units.scale != 1:
           locals =
                        input_string =
                                self = <taurus.external.pint.pint_local.unit.UnitRegistry object at 0x0548D5F0>
                            as_delta = True
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\external\pint\pint_local\util.py
         function = from_string
             line = [404]: def from_string(cls, input_string):
          -> line = [405]: return cls._from_string(input_string)
             line = [406]:
           locals =
                        input_string =
                                 cls = <class 'taurus.external.pint.pint_local.util.ParserHelper'>
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\external\pint\pint_local\compat\lrucache.py
         function = wrapper
             line = [128]: return result
          -> line = [129]: result = user_function(*args, **kwds)
             line = [130]: with lock:
           locals =
                                HITS = 0
                               cache = {(<class 'taurus.external.pint.pint_local.util.ParserHelper'>, u'1.68875 * Pa * [...]
                               stats = [24, 272]
                                kwds = {}
                                _len = <built-in function len>
                               typed = False
                                args = (<class 'taurus.external.pint.pint_local.util.ParserHelper'>, ' ')
                              MISSES = 1
                                 KEY = 2
                                NEXT = 1
                       nonlocal_root = [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]
                             maxsize = 100
                                link = None
                              RESULT = 3
                                 key = (<class 'taurus.external.pint.pint_local.util.ParserHelper'>, ' ')
                                lock = <_RLock owner=None count=0>
                       user_function = <function _from_string at 0x054F78B0>
                            make_key = <function _make_key at 0x0549AAB0>
                                PREV = 0
                           cache_get = <built-in method get of dict object at 0x054BAC90>
        ------------------------------------------------------------
         filename = C:\Python27\lib\site-packages\taurus\external\pint\pint_local\util.py
         function = _from_string
             line = [438]: gen = tokenizer(input_string)
          -> line = [439]: ret = build_eval_tree(gen).evaluate(cls.eval_token)
             line = [440]:
           locals =
                        input_string =
                                reps = False
                                 gen = <generator object tokenizer at 0x0659CB70>
                                 cls = <class 'taurus.external.pint.pint_local.util.ParserHelper'>
MainThread     WARNING  2017-01-12 10:50:13,841 TaurusRootLogger: Unknown unit "No unit (will be treated as dimensionless)"
MainThread     TRACE    2017-01-12 10:50:13,842 eu-000841:20000.lima/test/test.detectorModel: Subscribing to configuration events...
MainThread     WARNING  2017-01-12 10:50:13,880 TaurusRootLogger: Unknown unit "No unit (will be treated as dimensionless)"
```

If you want I can give you the win32 version of the LimaDetector bundled in a zip if the files addition supports ~13Mo

**Comment by cmft** [comment]
Hi @NexeyaSGara, 
You are right!! The  problem is with the unit,  "ºC"  is not valid in pint , as  you can see in this code

```
 from taurus.external.pint import Q_

 q = Q_(1, 'ºC')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)
# It works
q = Q_(10, 'degC')
``` 

If you change the unit of the affected attributes from "ºC" to "'degC" everything should be work.

**Comment by cmft** [comment]
I created a PR #389 to fix it. @NexeyaSGara , Could you check if it solves the bug?

**Comment by cpascual** [comment]
No answer from @NexeyaSGara ... It works ok for me, so I assume it works for him too...
