### ISSUE TITLE
Exception in lex.py when re-launching synoptics

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#364]
(from https://github.com/taurus-org/taurus/issues/360#issuecomment-271866054)
I must delete all the files of my profile/.taurus every time I want to launch a synoptic, because I'm getting error

```
MainThread     INFO     2017-01-11 14:14:47,079 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-01-11 14:14:47,186 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\Python27\lib\site-packages\taurus\qt\qtgui\icon\)
MainThread     WARNING  2017-01-11 14:14:47,207 root: taurusdatabase module is deprecated. Use taurusauthority instead
  File "D:\DEV\CEA-TECH\test.py", line 42, in <module>
    taurus.changeDefaultPollingPeriod(500)
  File "C:\Python27\lib\site-packages\taurus\core\taurushelper.py", line 669, in changeDefaultPollingPeriod
    Manager().changeDefaultPollingPeriod(period)
  File "C:\Python27\lib\site-packages\taurus\core\taurusmanager.py", line 384, in changeDefaultPollingPeriod
    plugin_classes = self._get_plugin_classes()
  File "C:\Python27\lib\site-packages\taurus\core\taurusmanager.py", line 338, in _get_plugin_classes
    m = __import__(full_module_name, fromlist=['*'], level=0)
  File "C:\Python27\lib\site-packages\taurus\core\simulation\__init__.py", line 42, in <module>
    from simfactory import *
  File "C:\Python27\lib\site-packages\taurus\core\simulation\simfactory.py", line 48, in <module>
    from taurus.core.taurusdatabase import TaurusDatabase
  File "C:\Python27\lib\site-packages\taurus\core\taurusdatabase.py", line 34, in <module>
    traceback.print_stack()
<module 'jdraw_lextab' from 'C:\Users\sgara\.taurus\jdraw_yacctab.py'>
<module 'jdraw_lextab' from 'C:\Users\sgara\.taurus\jdraw_yacctab.py'>
Traceback (most recent call last):
  File "D:\DEV\CEA-TECH\test.py", line 50, in <module>
    ui.setupUi(Test)
  File "D:\DEV\CEA-TECH\test.py", line 34, in setupUi
    self.taurusJDrawSynopticsView.setModel(_translate("Test", "jdraw_test.jdw", None))
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\graphic\jdraw\jdraw_view.py", line 382, in setModel
    scene = jdraw_parser.parse(filename, factory)
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\graphic\jdraw\jdraw_parser.py", line 352, in parse
    _, p = new_parser()
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\graphic\jdraw\jdraw_parser.py", line 332, in new_parser
    l = lex.lex(lextab=jdraw_lextab, **common_kwargs)
  File "C:\Python27\lib\site-packages\ply-3.6-py2.7.egg\ply\lex.py", line 909, in lex
    baselextab = lextab.split('.')[-1]
AttributeError: 'module' object has no attribute 'split'
```

**Comment by cpascual** [comment]
I cannot reproduce this problem anymore with the current develop, so I am closing it.
