### ISSUE TITLE
taurus.qt.qtgui fails to import if PyTango is not installed

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#398]
To reproduce, **uninstall PyTango** and do:

```
:~$ python -c 'import taurus.qt.qtgui'
MainThread     INFO     2017-02-07 09:50:03,482 TaurusRootLogger: Using "PyQt4" for Qt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/__init__.py", line 35, in <module>
    import icon as __icon
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/__init__.py", line 32, in <module>
    from catalog import QIconCatalog
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/catalog.py", line 31, in <module>
    from taurus.qt.qtgui.input import GraphicalChoiceWidget
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/input/__init__.py", line 32, in <module>
    from .tauruscheckbox import *
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/input/tauruscheckbox.py", line 33, in <module>
    from taurus.qt.qtgui.base import TaurusBaseWritableWidget
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/__init__.py", line 31, in <module>
    from .taurusbase import *
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 56, in <module>
    from taurus.qt.qtgui.util import ActionFactory
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/util/__init__.py", line 33, in <module>
    from .tauruscolor import *
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/util/tauruscolor.py", line 40, in <module>
    from taurus.core.tango import DevState  # TODO: Tango-centric
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/__init__.py", line 108, in <module>
    from enums import *
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/enums.py", line 43, in <module>
    import PyTango
  File "/usr/lib/python2.7/dist-packages/PyTango.py", line 5, in <module>
    import tango
ImportError: No module named tango

```

**Comment by cpascual** [comment]
As you may notice, there is already a TODO in `taurus/qt/qtgui/util/tauruscolor.py`:

`from taurus.core.tango import DevState  # TODO: Tango-centric`
