### ISSUE TITLE
Taurustrend: force reading period not working

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#475]
Hi, 

Tested with Taurus 4.0.4-alpha on Debian 9, Tango 9.2

The "force reading period" option from taurustrend context menu has no effect; attributes are still updated only on event received.

Sergi Rubio

**Comment by cmft** [comment]
Hi @sergirubio ,
It is a bug, taurustrend is reporting an exception.

```
taurustrend sys/tg_test/1/float_scalar -r100
MainThread     INFO     2017-06-22 12:10:59,333 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-06-22 12:10:59,832 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/plot/taurustrend.py", line 428, in handleEvent
    elif model.isNumeric():
AttributeError: 'TaurusTrendsSet' object has no attribute 'isNumeric'
```
