### ISSUE TITLE
Cannot create TangoAttribute if unit is set to "%" 

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#493]
Attributes with "%" set in the tango system to "%" are unusable.

To reproduce:
- set the unit of attribute sys/tg_test/1/ampli to "%"
- then do: `import taurus;taurus.Attribute("sys/tg_test/1/ampli")` 

```
MainThread     DEBUG    2017-07-12 09:12:21,607 TangoFactory: Error creating attribute sys/tg_test/1/long_scalar
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangofactory.py", line 383, in getAttribute
    attr = attr_klass(full_attr_name, dev, **kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangoattribute.py", line 285, in __init__
    self._decodeAttrInfoEx(attr_info)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangoattribute.py", line 905, in _decodeAttrInfoEx
    units = self._unit_from_tango(i.unit)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangoattribute.py", line 956, in _unit_from_tango
    return UR.parse_units(unit)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/registry.py", line 763, in parse_units
    units = self._parse_units(input_string, as_delta)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/registry.py", line 873, in _parse_units
    return super(NonMultiplicativeRegistry, self)._parse_units(input_string, as_delta)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/registry.py", line 781, in _parse_units
    units = ParserHelper.from_string(input_string)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/util.py", line 414, in from_string
    return cls._from_string(input_string)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/compat/lrucache.py", line 129, in wrapper
    result = user_function(*args, **kwds)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/external/pint/pint_local/util.py", line 449, in _from_string
    ret = build_eval_tree(gen).evaluate(cls.eval_token)
AttributeError: 'NoneType' object has no attribute 'evaluate'
```

**Comment by cpascual** [comment]
It seems that we need to add some protection in  `_decodeAttrInfoEx`
