### ISSUE TITLE
Error in model chooser

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#503]
For me this happens when using the model chooser with taurusgui --new-gui and more preciselly when selecting a model for a new panel in the wizard. I get the following error. I use the standard Debian 9 packages and taurus from develop.

```
Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/taurusgui/paneldescriptionwizard.py", line 429, in showModelChooser
    parent=self, asMimeData=True)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/panel/taurusmodelchooser.py", line 322, in modelChooserDlg
    parent=parent, selectables=selectables, host=host, singleModel=singleModel)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/panel/taurusmodelchooser.py", line 174, in __init__
    selectables=selectables, buttonsPos=Qt.Qt.BottomToolBarArea)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/panel/taurusmodelchooser.py", line 57, in __init__
    perspective=taurus.core.taurusbasetypes.TaurusElementType.Device)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/tree/taurustree.py", line 44, in __init__
    perspective=perspective, proxy=proxy)
  File "/home/zreszela/workspace/taurus/lib/taurus/core/util/object.py", line 49, in call__init__
    klass.__init__(self, *args, **kw)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/tree/qtree.py", line 199, in __init__
    perspective=perspective, proxy=proxy)
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/model/qbasemodel.py", line 318, in __init__
    self._viewWidget = self.createViewWidget()
  File "/home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/tree/qtree.py", line 239, in createViewWidget
    h.setResizeMode(0, Qt.QHeaderView.Stretch)
  File "/usr/lib/python2.7/dist-packages/qtpy/_patch/qheaderview.py", line 83, in setResizeMode
    raise Exception('setResizeMode is only available in Qt4. Use '
Exception: setResizeMode is only available in Qt4. Use setSectionResizeMode instead.
```

**Comment by reszelaz** [comment]
Actually I was using cpascual:fix-250 branch that I wrongly assumed that was rebased on the latest develop. This bug was fixed with #473. So ignore it...
