### ISSUE TITLE
taurusimage: bug when trying to export data

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#518]
taurusimage: bug when trying to export data.

When using the option "export data" from the contextual menu, taurusimage does not deal correctly with the name of the exported data file. The following bug is reported:

<pre>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/guiqwt/qthelpers.py", line 71, in exec_image_save_dialog
    io.imwrite(filename, data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/guiqwt/io.py", line 414, in imwrite
    iohandler.get_writefunc(ext)(fname, arr, **kwargs)
  File "/usr/lib/python2.7/dist-packages/guiqwt/io.py", line 155, in get_writefunc
    ftype = self._get_filetype(ext)
  File "/usr/lib/python2.7/dist-packages/guiqwt/io.py", line 143, in _get_filetype
    raise RuntimeError("Unsupported file type: '%s'" % ext)
RuntimeError: Unsupported file type: ''
</pre>

**Comment by cpascual** [comment]
Confirmed
