### ISSUE TITLE
Images from a Tango device are not shown in a taurusdevicepanel

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#520]
Images from a Tango device are not shown by taurusdevicepanel in the edit mode.
This can be seen by using the button "edit" from the short image, in the 
```
taurusdevicepanel sys/tg_test/1
```

What happens is that the table write value is not initialized when the Tango device is restarted.
But then, in taurusdevicepanel, the tables are not visible, and if trying to change a value, the following error is reported:

<pre>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/table/taurusvaluestable.py", line 474, in createEditor
    editor._updateValidator(index.model().getAttr())
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/table/taurusvaluestable.py", line 582, in _updateValidator
    validator.setBottom(self._min_range)
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/util/validator.py", line 88, in setBottom
    self._bottom = Quantity(bottom)
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/pint/pint_local/quantity.py", line 77, in __new__
    inst._magnitude = _to_magnitude(value, inst.force_ndarray)
  File "/usr/local/lib/python2.7/dist-packages/taurus/external/pint/pint_local/compat/__init__.py", line 84, in _to_magnitude
    raise TypeError('Invalid magnitude for Quantity: {0!r}'.format(value))
TypeError: Invalid magnitude for Quantity: None
</pre>

----

It can also be reproduced with the taurusvaluestable:

python -m taurus.qt.qtgui.table.taurusvaluestable sys/tg_test/1/short_image
The table is all white.

**Comment by cpascual** [comment]
Note that this is not (strictly speaking) a bug. The TangoTest DS when freshly started returns the following:
```python
In [10]: v = tango.DeviceProxy('sys/tg_test/1').read_attribute('short_scalar')

In [11]: v.w_value
Out[11]: 0

In [12]: v.w_dimension
Out[12]: AttributeDimension(dim_x = 1, dim_y = 0)
```

...and the TaurusValuesTable widget is (obligingly) showing a table with 0 rows for editting (!)

IMHO, this is more an issue of how the TangoTest DS initializes the its writable spectrum and image attributes

That said, we could consider an enhancement of allowing the user of a TaurusValuesTable to set the table dimensions explicitly when in write mode. This would make the widget more usable in cases like this.
