### ISSUE TITLE
bug: taurusplot retrieve saved settings 

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#522]
The retrieve saved settings does not work some times.

How to reproduce:
In taurus docker cpascual/taurus-test:debian9
<pre>
taurusplot 'eval:Q(rand(333), "mm")' sys/tg_test/1/wave
</pre>

- Modify the settings with plot configuration. (from the contextual menu of taurusplot)
- Save current settings 
- Remodify settings with plot configuration
- Retrieve saved settings

The first time the settings are not retrieved correctly:
<pre>
taurusplot 'eval:Q(rand(333), "mm")' sys/tg_test/1/wave
MainThread     INFO     2017-07-19 13:07:24,667 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-07-19 13:07:24,751 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/plot/taurusplot.py", line 2489, in loadConfig
    self.applyConfig(configdict)
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/plot/taurusplot.py", line 2412, in applyConfig
    self.setCurveAppearanceProperties(configdict["CurveProp"])
  File "/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/plot/taurusplot.py", line 2256, in setCurveAppearanceProperties
    c = self.curves[name]
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/util/containers.py", line 258, in __getitem__
    return dict.__getitem__(self, key.lower())
KeyError: 'eval:q(rand(333), "mm")'
</pre>

**Comment by mrosanes** [comment]
The problem is that TaurusPlot.curves is a caseless dict, which is Tango-centric. 
This is already marked with a TODO in the code.

In this case we are using a case sensitive eval model and the curve is not found when trying to restore settings.

**Comment by cpascual** [comment]
I think this is related to #668

**Comment by cpascual** [comment]
Bug confirmed.
This goes into the more general and known problem of TaurusPlot /TaurusTrend not properly supporting case-sensitive models.

IMHO, we should focus on making sure that the problem is not ported to the new plotting widgets in TEP17, but not putting too much effort in fixing it for the qet-based widgets
