### ISSUE TITLE
[taurusdemo] Runtime Error: wrapped C/C++ object has been deleted

### ISSUE THREAD

**Issue by LJBD** [taurus-org/taurus#535]
Hello!

Still testing #510. I've launched `taurusdemo`, clicked on "Frame" button, got a frame with all signals connected to a TangoTest Device and upon closing this widget, I've got a flood of `RuntimeErrors`.
It's the same error as in #215 .

It looks like the widgets are deleted, but the events mechanism is not closed properly.

My setup is:
* CentOS 7
* Tango 9.2.5a
* PyTango 9.2.1
* zeromq 4.1.4
* omniORB 4.2.2
* Qt 4.8.5
* PyQt 4.10.1

```python
[ljbd@ble-test taurus]$ taurusdemo 
MainThread     INFO     2017-07-21 10:38:29,259 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-07-21 10:38:29,457 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/icon/)
MainThread     WARNING  2017-07-21 10:38:29,677 TaurusRootLogger: /home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/util/tauruswidgetfactory.py:111: DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)

Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/taurusled.py", line 251, in handleEvent
    self.controller().handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/taurusled.py", line 102, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/taurusled.py", line 107, in update
    self._updateDisplay(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/taurusled.py", line 128, in _updateDisplay
    widget.ledStatus = status
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/qled.py", line 160, in setLedStatus
    self._refresh()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/qled.py", line 107, in _refresh
    self.setPixmap(pixmap)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/qpixmapwidget.py", line 124, in setPixmap
    self.update()
RuntimeError: wrapped C/C++ object of type TaurusLed has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted
Traceback (most recent call last):
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/taurusbase.py", line 349, in filterEvent
    self.handleEvent(*evt)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 309, in handleEvent
    ctrl.handleEvent(evt_src, evt_type, evt_value)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 112, in handleEvent
    self.update()
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py", line 129, in update
    self._updateForeground(widget)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 100, in _updateForeground
    self._trimmedText = self._shouldTrim(label, text)
  File "/home/ljbd/lib/python2.7/site-packages/taurus-4.1.0-py2.7.egg/taurus/qt/qtgui/display/tauruslabel.py", line 109, in _shouldTrim
    font_metrics = Qt.QFontMetrics(label.font())
RuntimeError: wrapped C/C++ object of type TaurusLabel has been deleted

```

**Comment by LJBD** [comment]
The same thing happens after closing a GroupBox or a GroupWidget.

**Comment by cpascual** [comment]
I cannot reproduce this on my machine (a debian9 using an external Tango7 Tango host) nor in the cpascual/taurus-test:debian9 docker... (also a debian9, running the DB on localhost)
