### ISSUE TITLE
Taurusform: Error writing value to epics attribute 

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#588]
To reproduce:
(Using the cpascual/taurus-test:debian-stretch docker image with Taurus 4.1.2a)

launch `taurusform epics:XXX:a` and try to write a new value with the write widget.

The traceback is similar to this:

```
Traceback (most recent call last):
  File "/home/cpascual/src/taurus/lib/taurus/qt/qtgui/dialog/taurusmessagebox.py", line 191, in wrapped
    return fn(*args, **kwargs)
  File "/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 977, in go
    self.getTaurusManager().applyPendingOperations(ops)
  File "/home/cpascual/src/taurus/lib/taurus/core/taurusmanager.py", line 381, in applyPendingOperations
    o.execute()
  File "/home/cpascual/src/taurus/lib/taurus/core/taurusoperation.py", line 82, in execute
    self.attr.write(self.value)
  File "/home/cpascual/src/taurus/lib/taurus/core/epics/epicsattribute.py", line 201, in write
    self.__pv.put(value, wait=True)
  File "/home/cpascual/.virtualenvs/epics/local/lib/python2.7/site-packages/epics/pv.py", line 395, in put
    callback_data=callback_data)
  File "/home/cpascual/.virtualenvs/epics/local/lib/python2.7/site-packages/epics/ca.py", line 463, in wrapper
    return fcn(*args, **kwds)
  File "/home/cpascual/.virtualenvs/epics/local/lib/python2.7/site-packages/epics/ca.py", line 1443, in put
    data[0] = type(data[0])(value)
TypeError: float() argument must be a string or a number
```

**Comment by napppoli** [comment]
It seems to me, the cause of the problem here is that if you have EPICS attribute without unit(=EGU field of EPICS PV), getValue function of tauruslineedit.py sets unit of validator instead of PV's unit, but this validator's unit is actually None at default.
```
                    if q.unitless:
                        q = Quantity(q.magnitude, val.units)
```
As a result, it raises exception and getValue function returns None to 'value' variable on ca.py, which raises this issue's error.

I know nothing about the case for Tango attributes without units, but I guess the same problem might happen. How is it for the case for Tango? Is the validator also set None at first for an attribute without unit?

My local solution is that you modify the above code to following:
```
                    if q.unitless:
                        try:
                            q = Quantity(q.magnitude, val.units)
                        except:
                            q = Quantity(q.magnitude, None)
```
It fixes the problem on my local environment, but it is kind of a workaround and better solution may exist.

**Comment by cmft** [comment]
Hi @napppoli,
I believe the problems are related with the validator that is not well set. 
``` 
             if model_type in [DataType.Integer, DataType.Float]:
                 try:
+                    if not isinstance(val, PintValidator):
+                        self._updateValidator(model_obj)
+                        val = self.validator()
 ```

**Comment by cmft** [comment]
By the way:
Our  test epics configuration seems to be wrong (taurus uses upper_ctrl_limit and lower_ctrl_limit as attributes range and it seems that epics is defaulting them to 0,0 instead of the what taurus expected  None, None)
```
n [15]: a = epics.PV('XXX:a')

In [16]: print a.info
== XXX:a  (time_double) ==
   value      = 10
   char_value = '10'
   count      = 1
   nelm       = 1
   type       = time_double
   units      = 
   precision  = 0
   host       = localhost:5064
   access     = read/write
   status     = 0
   severity   = 0
   timestamp  = 1519898032.641 (2018-03-01 09:53:52.64140)
   posixseconds        = 1519898032.0
   nanoseconds= 641396446
   upper_ctrl_limit    = 0.0
   lower_ctrl_limit    = 0.0
   upper_disp_limit    = 0.0
   lower_disp_limit    = 0.0
   upper_alarm_limit   = nan
   lower_alarm_limit   = nan
   upper_warning_limit = nan
   lower_warning_limit = nan
   PV is internally monitored, with 0 user-defined callbacks:
=============================
```
