### ISSUE TITLE
dependencies check and lxml

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#612]
Hi,
I noticed a problem when launching taurusgui.

Before that, when I check the dependencies, I got:

```
python -c 'import taurus; taurus.check_dependencies()'
Dependencies for taurus 4.1.1:
	[*] numpy>=1.1

Extras:
Dependencies for taurus[taurus-epics]:
	[*] numpy>=1.1
	[*] pyepics>=3.2.4; extra == "taurus-epics"
Dependencies for taurus[taurus-h5file]:
	[*] numpy>=1.1
	[*] h5file; extra == "taurus-h5file"
Dependencies for taurus[taurus-qt]:
	[*] numpy>=1.1
	[*] guiqwt>=3; extra == "taurus-qt"
	[*] spyder>=3.0; extra == "taurus-qt"
	[*] qtpy>=1.2.1; extra == "taurus-qt"
	[*] lxml>=2.1; extra == "taurus-qt"
	[*] ply>=2.3; extra == "taurus-qt"
	[*] PyQt4>=4.8 (not in PyPI)
	[*] PyQt4.Qwt5>=5.2 (not in PyPI)
Dependencies for taurus[taurus-tango]:
	[*] numpy>=1.1
	[*] PyTango>=7.1; extra == "taurus-tango"
```

But when I launch `taurusgui --new-gui` (v4.1.1), I got an error:

```
$ taurusgui --new-gui
MainThread     INFO     2017-11-06 21:20:50,357 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-11-06 21:20:50,436 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/tango9/.local/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
Traceback (most recent call last):
  File "/home/tango9/.local/bin/taurusgui", line 7, in <module>
    from taurus.qt.qtgui.taurusgui.taurusgui import main
  File "/home/tango9/.local/lib/python2.7/site-packages/taurus/qt/qtgui/taurusgui/__init__.py", line 55, in <module>
    import utils
  File "/home/tango9/.local/lib/python2.7/site-packages/taurus/qt/qtgui/taurusgui/utils.py", line 33, in <module>
    from lxml import etree
ImportError: No module named lxml
```

The problem here is dependencies seems OK but they are not (lxml version seems too old).

I found 2 solutions:
- installing lxml through pip:

```
pip install lxml
Collecting lxml
  Downloading lxml-4.1.1-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 253kB/s 
Installing collected packages: lxml
Successfully installed lxml-4.1.1
```

- installing lxml through apt-get (v3.7.1-1):

```
 sudo apt-get install python-lxml
[sudo] Mot de passe de tango9 : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
The following additional packages will be installed:
  python-bs4 python-html5lib python-webencodings
Paquets suggérés :
  python-genshi python-lxml-dbg python-lxml-doc
Les NOUVEAUX paquets suivants seront installés :
  python-bs4 python-html5lib python-lxml python-webencodings
0 mis à jour, 4 nouvellement installés, 0 à enlever et 656 non mis à jour.
Il est nécessaire de prendre 1 088 ko dans les archives.
Après cette opération, 4 211 ko d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] 
Réception de:1 http://ftp.fr.debian.org/debian stretch/main amd64 python-bs4 all 4.5.3-1 [86,7 kB]
Réception de:2 http://ftp.fr.debian.org/debian stretch/main amd64 python-webencodings all 0.5-2 [10,3 kB]
Réception de:3 http://ftp.fr.debian.org/debian stretch/main amd64 python-html5lib all 0.999999999-1 [88,0 kB]
Réception de:4 http://ftp.fr.debian.org/debian stretch/main amd64 python-lxml amd64 3.7.1-1 [903 kB]
1 088 ko réceptionnés en 1s (918 ko/s)
Sélection du paquet python-bs4 précédemment désélectionné.
(Lecture de la base de données... 144645 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python-bs4_4.5.3-1_all.deb ...
Dépaquetage de python-bs4 (4.5.3-1) ...
Sélection du paquet python-webencodings précédemment désélectionné.
Préparation du dépaquetage de .../python-webencodings_0.5-2_all.deb ...
Dépaquetage de python-webencodings (0.5-2) ...
Sélection du paquet python-html5lib précédemment désélectionné.
Préparation du dépaquetage de .../python-html5lib_0.999999999-1_all.deb ...
Dépaquetage de python-html5lib (0.999999999-1) ...
Sélection du paquet python-lxml précédemment désélectionné.
Préparation du dépaquetage de .../python-lxml_3.7.1-1_amd64.deb ...
Dépaquetage de python-lxml (3.7.1-1) ...
Paramétrage de python-bs4 (4.5.3-1) ...
Paramétrage de python-lxml (3.7.1-1) ...
Paramétrage de python-webencodings (0.5-2) ...
Paramétrage de python-html5lib (0.999999999-1) ...
```

I choose the second one which seems to be prefered (see #552 in comment https://github.com/taurus-org/taurus/issues/552#issuecomment-325902475).

**Comment by PhilLAL** [comment]
This issue is perhaps linked to #376

**Comment by cpascual** [comment]
What was the version of lxml that you originally had? 

And how was it installed in the first place?

Anyway... this is a bit strange because `taurus.check_dependencies()` reported that `lxml >=2.1` was found, but the traceback says `ImportError: No module named lxml`
I suspect that something in your system was a bit messed up regarding this module...

(now the question is if it was taurus who messed it up ;) )

**Comment by PhilLAL** [comment]
That is a good question.
Since I've done theses tests on a VM, I restored to a state before lxml reinstallation.
I do not find any lxml module:

```
$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named lxml
```

It seems lxml is not installed but detected however.
Indeed, I did not explicitely install lxml.

Here are the steps I followed to install taurus:
```
sudo apt-get update && sudo apt-get install -y python-pip
sudo apt-get install -y python-pytango python-qt4 python-qwt5-qt4 python-qtpy qt4-designer pyqt4-dev-tools
pip install taurus
echo 'PATH="${HOME}/.local/bin:$PATH"' >> ~/.bashrc
echo 'export PATH' >> ~/.bashrc
echo 'PYTHONPATH=$HOME/taurus' >> ~/.bashrc
echo 'export PYTHONPATH' >> ~/.bashrc
sudo apt-get update && sudo apt-get install -y python-pip
```

**Comment by cpascual** [comment]
> Since I've done theses tests on a VM, I restored to a state before lxml reinstallation.(...) It seems lxml is not installed but detected however

As I say, it looks like something was unclean regarding the lxml installation in your system 
can you please run  the following commands and report the result? (in the system before lxml reinstallation)

```
python -c 'import pkg_resources; print pkg_resources.require("lxml")'
python -c 'import lxml'
python -c 'import taurus; taurus.check_dependencies()'
```

**Comment by PhilLAL** [comment]
Here is the output of these three commands:

```
tango9@tango9:~/taurus$ python -c 'import pkg_resources; print pkg_resources.require("lxml")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lxml' distribution was not found and is required by the application
tango9@tango9:~/taurus$ python -c 'import lxml'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named lxml
tango9@tango9:~/taurus$ python -c 'import taurus; taurus.check_dependencies()'
Dependencies for taurus 4.1.1:
    [*] numpy>=1.1

Extras:
Dependencies for taurus[taurus-epics]:
    [*] numpy>=1.1
    [*] pyepics>=3.2.4; extra == "taurus-epics"
Dependencies for taurus[taurus-h5file]:
    [*] numpy>=1.1
    [*] h5file; extra == "taurus-h5file"
Dependencies for taurus[taurus-qt]:
    [*] numpy>=1.1
    [*] guiqwt>=3; extra == "taurus-qt"
    [*] spyder>=3.0; extra == "taurus-qt"
    [*] qtpy>=1.2.1; extra == "taurus-qt"
    [*] lxml>=2.1; extra == "taurus-qt"
    [*] ply>=2.3; extra == "taurus-qt"
    [*] PyQt4>=4.8 (not in PyPI)
    [*] PyQt4.Qwt5>=5.2 (not in PyPI)
Dependencies for taurus[taurus-tango]:
    [*] numpy>=1.1
    [*] PyTango>=7.1; extra == "taurus-tango"
```

I also ran these 2 commands in any case it helps...

```
tango9@tango9:~/taurus$ pip list | grep lxml
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
tango9@tango9:~/taurus$ dpkg --get-selections | grep lxml
tango9@tango9:~/taurus$
```

**Comment by cmft** [comment]
I confirm the  bug. 

The problem is in the  `check_dependencies` implementation where the `str` cast does not work as  we expected. It returns string like `guiqwt>=3; extra == "taurus-qt" ` and this string did not raise an exception when is evaluating with `pkg_resources.require(str(r))`

See the code:
```
import pkg_resources
d = pkg_resources.get_distribution('taurus')

d.requires(extras=['taurus-qt'])
for r in d.requires(extras=['taurus-qt']):
    print str(r)

numpy>=1.1
guiqwt>=3; extra == "taurus-qt"
spyder>=3.0; extra == "taurus-qt"
qtpy>=1.2.1; extra == "taurus-qt"
lxml>=2.1; extra == "taurus-qt"
ply>=2.3; extra == "taurus-qt"

```

**Comment by cmft** [comment]
Changing  the `pkg_resources.require` calls from `pkg_resources.require(str(r))` to 
`pkg_resources.require(r.name + str(r.specifier))` should solve the bug.

**Comment by cpascual** [comment]
> good find!

**Comment by cmft** [comment]
I will, but  I found troubles with my proposal the `pkg_resources` API is different between versions. `name` and  `specifier` are  not always expose.

**Comment by cpascual** [comment]
After looking at this together with @cmft , we think we found (to be confirmed):

- installing from a tar.gz generated by Appveyor (such as the one in PyPI) produces the problematic requires
- installing from a tar.gz generated on a debian (or straigh from a repo checkout in debian) is ok.

@cmft will do further tests

**Comment by cmft** [comment]
After the test, It looks like the problem are reproduced when taurus is installed from a tarball generated with  a `sdist` command.  I reproduced the error in both scenarios:
- installing from the Appveyor tar file
- and generating one from a fresh clone in a debian container.

The problem can not  be reproduce when you install taurus usisg the source code.

**Comment by cpascual** [comment]
Ok, as a very ugly but clean workaround, I propose to replace 

```python
pkg_resources.require(str(r))
```

by

```python
pkg_resources.require(str(r).split(';')[0])
```

**Comment by cpascual** [comment]
I created a PR (#615) to fix this. Can you please check? (you may use the tar.gz [from the appveyor build](https://ci.appveyor.com/project/taurusorg/taurus/build/1.0.433/job/wtjg5qle4fpg2jw0/artifacts))
