### ISSUE TITLE
epics import errors, even if no epics is used at all

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#620]
Calling a taurusdevicepanel on a Tango device with log level DEBUG these epics errors apeared on stdout. Should be epics imported when no epics model is used?

```
DEBUG    2017-11-17 09:56:23,718 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-11-17 09:56:23,718 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
DEBUG    2017-11-17 09:56:23,718 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-11-17 09:56:23,718 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
DEBUG    2017-11-17 09:56:23,719 TaurusManager: Failed to inspect taurus.core.epics
MainThread     DEBUG    2017-11-17 09:56:23,719 TaurusManager: Failed to inspect taurus.core.epics
DEBUG    2017-11-17 09:56:23,719 TaurusManager: Details:
Traceback (most recent call last):
  File "taurus/core/taurusmanager.py", line 343, in _get_plugin_classes
    globals(), locals(), ['*'])
  File "taurus/core/epics/__init__.py", line 70, in <module>
    from epicsfactory import *
  File "taurus/core/epics/epicsfactory.py", line 34, in <module>
    import epics
ImportError: No module named epics
MainThread     DEBUG    2017-11-17 09:56:23,719 TaurusManager: Details:
Traceback (most recent call last):
  File "taurus/core/taurusmanager.py", line 343, in _get_plugin_classes
    globals(), locals(), ['*'])
  File "taurus/core/epics/__init__.py", line 70, in <module>
    from epicsfactory import *
  File "taurus/core/epics/epicsfactory.py", line 34, in <module>
    import epics

```

**Comment by cpascual** [comment]
IMHO, it is ok. These are no errors, just debug messages that show tracebacks.

These debug messages occur because the taurus-epics scheme is installed alongside with taurus, but since it is actually optional, pyepics may not be installed.

Eventually, we intend to move the schemes to properly independent plugins (taurus-epics, taurus-tango, etc) When that comes, these messages will disappear because installing the plugin will "force" to install its dependencies.

I am closing this. If you need any more clarification feel free to reopen.
