### ISSUE TITLE
Windows : At least 3 consecutive events from model "A/B/C" have been dropped. This attribute may have problems

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#645]
Hello,
we encountered a problem with Taurus on Windows.
It is perhaps linked to #643 

I wrote a test program: it displays the state of TangoTest device server and shows a button allowing to switch the state from `RUNNING` to `FAULT`.
Here is the code : https://owncloud.lal.in2p3.fr/index.php/s/FUjheZEqfcVS1Fq/download

When I launch it under GNU/Linux, it starts without any issue.
On Windows, here is the output we got when launching the same program:
```
$> python graphiqueTendance.py
MainThread     INFO     2017-12-12 11:22:27,533 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-12-12 11:22:27,674 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from c:\PATH-TO-TAURUS\taurus-develop\lib\taurus\qt\qtgui\icon\)
MainThread     WARNING  2017-12-12 11:22:27,767 [TANGO_HOST:PORT].sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     WARNING  2017-12-12 11:22:27,907 [TANGO_HOST:PORT].sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     WARNING  2017-12-12 11:22:59,855 TaurusTrendsSet.sys/tg_test/1/long64_scalar: At least 3 consecutive events from model "sys/tg_test/1/long64_scalar" have been dropped. This attribute may have problems
Future occurrences will be silently ignored
MainThread     WARNING  2017-12-12 11:22:59,875 TaurusTrendsSet.sys/tg_test/1/long_scalar: At least 3 consecutive events from model "sys/tg_test/1/long_scalar" have been dropped. This attribute may have problems
Future occurrences will be silently ignored
```

The computer is connected with RJ45 high bandwidth, in an office next to mine on the same network.

**Comment by cpascual** [comment]
First check if you can read sys/tg_test/1/long_scalar using jive on windows
Then check if you can do it with PyTango:

```
import tango
d = tango.DeviceProxy('sys/tg_test/1')
print d.read_attribute('long_scalar')
```

**Comment by cpascual** [comment]
Also, launch your application adding  `python graphiqueTendance.py --taurus-log-level=trace` to get more info on why the events were dropped

**Comment by PhilLAL** [comment]
Hi,
your first suggestion seems to work (https://github.com/taurus-org/taurus/issues/645#issuecomment-351410463):

```
>>> import tango
>>> d = tango.DeviceProxy('sys/tg_test/1')
>>> print d.read_attribute('long_scalar')
DeviceAttribute[
data_format = tango._tango.AttrDataFormat.SCALAR
      dim_x = 1
      dim_y = 0
 has_failed = False
   is_empty = False
       name = 'long_scalar'
    nb_read = 1
 nb_written = 1
    quality = tango._tango.AttrQuality.ATTR_VALID
r_dimension = AttributeDimension(dim_x = 1, dim_y = 0)
       time = TimeVal(tv_nsec = 0, tv_sec = 1513235814, tv_usec = 310298)
       type = tango._tango.CmdArgType.DevLong
      value = 200
    w_dim_x = 1
    w_dim_y = 0
w_dimension = AttributeDimension(dim_x = 1, dim_y = 0)
    w_value = 0]
```

Here is the second output with trace (https://github.com/taurus-org/taurus/issues/645#issuecomment-351411756). We apologize, we do no have the reflex to launch it yet, it will come soon :))

```
$> python graphiqueTendance.py --taurus-log-level=trace
MainThread     INFO     2017-12-14 13:02:56,855 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2017-12-14 13:02:56,999 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from c:\PATH-TO-TAURUS\taurus\lib\taurus\qt\qtgui\icon\)
MainThread     TRACE    2017-12-14 13:02:57,019 TaurusManager: reInit()
MainThread     DEBUG    2017-12-14 13:02:57,023 TaurusManager.TaurusTP: Starting TaurusTP.W001
MainThread     DEBUG    2017-12-14 13:02:57,023 TaurusManager.TaurusTP: Starting TaurusTP.W002
MainThread     DEBUG    2017-12-14 13:02:57,023 TaurusManager.TaurusTP: Starting TaurusTP.W003
MainThread     DEBUG    2017-12-14 13:02:57,026 TaurusManager.TaurusTP: Starting TaurusTP.W004
MainThread     DEBUG    2017-12-14 13:02:57,026 TaurusManager.TaurusTP: Starting TaurusTP.W005
MainThread     DEBUG    2017-12-14 13:02:57,026 TaurusApplication: Failed to load sardana extensions
Traceback (most recent call last):
  File "c:\PATH-TO-TAURUS\taurus\lib\taurus\qt\qtgui\application\taurusapplication.py", line 263, in __registerExtensions
    import sardana.taurus.qt.qtcore.tango.sardana
ImportError: No module named sardana.taurus.qt.qtcore.tango.sardana
MainThread     DEBUG    2017-12-14 13:02:57,035 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-12-14 13:02:57,035 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2017-12-14 13:02:57,035 TaurusManager: Failed to inspect taurus.core.epics
MainThread     DEBUG    2017-12-14 13:02:57,039 TaurusManager: Details:
Traceback (most recent call last):
  File "c:\PATH-TO-TAURUS\taurus\lib\taurus\core\taurusmanager.py", line 343, in _get_plugin_classes
    globals(), locals(), ['*'])
  File "c:\PATH-TO-TAURUS\taurus\lib\taurus\core\epics\__init__.py", line 70, in <module>
    from epicsfactory import *
  File "c:\PATH-TO-TAURUS\taurus\lib\taurus\core\epics\epicsfactory.py", line 34, in <module>
    import epics
ImportError: No module named epics
MainThread     DEBUG    2017-12-14 13:02:57,042 TaurusManager: Found plugin EvaluationFactory
MainThread     DEBUG    2017-12-14 13:02:57,042 TaurusManager: Found plugin ResourcesFactory
MainThread     DEBUG    2017-12-14 13:02:57,042 TaurusManager: Found plugin TangoFactory
MainThread     DEBUG    2017-12-14 13:02:57,062 TaurusPlot: New replot period is 0.25 seconds
MainThread     WARNING  2017-12-14 13:02:57,131 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:02:57,131 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: UndefinedUnitError()
MainThread     TRACE    2017-12-14 13:02:57,131 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Subscribing to configuration events...
MainThread     DEBUG    2017-12-14 13:02:57,200 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:02:57,226 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer::start()
TimerLoop 1    DEBUG    2017-12-14 13:02:57,227 TaurusPollingTimer[3000].Timer on _pollAttributes: Timer thread starting
MainThread     WARNING  2017-12-14 13:02:57,244 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:02:57,244 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: UndefinedUnitError()
MainThread     TRACE    2017-12-14 13:02:57,246 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Subscribing to configuration events...
MainThread     DEBUG    2017-12-14 13:02:57,278 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:02:57,309 TaurusPlot: stopping the timer (in updateCurves)
MainThread     DEBUG    2017-12-14 13:02:57,318 TaurusPlot: stopping the timer (in resizeEvent)
MainThread     DEBUG    2017-12-14 13:02:57,319 TaurusPlot: (re)starting the timer (in showEvent)
MainThread     DEBUG    2017-12-14 13:02:57,358 TaurusPlot: attaching raw data with name sys/tg_test/1/long_scalar[0]
MainThread     DEBUG    2017-12-14 13:02:57,361 TaurusPlot: Now Zooming on Y1
MainThread     DEBUG    2017-12-14 13:03:09,163 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:09,164 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:09,167 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:09,167 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:19,177 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:19,178 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:19,181 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:19,183 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:29,200 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
MainThread     WARNING  2017-12-14 13:03:29,200 TaurusTrendsSet.sys/tg_test/1/long64_scalar: At least 3 consecutive events from model "sys/tg_test/1/long64_scalar" have been dropped. This attribute may have problems
Future occurrences will be silently ignored
Dummy-1        DEBUG    2017-12-14 13:03:29,201 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
Dummy-1        DEBUG    2017-12-14 13:03:29,204 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:29,207 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
MainThread     WARNING  2017-12-14 13:03:29,209 TaurusTrendsSet.sys/tg_test/1/long_scalar: At least 3 consecutive events from model "sys/tg_test/1/long_scalar" have been dropped. This attribute may have problems
Future occurrences will be silently ignored
MainThread     DEBUG    2017-12-14 13:03:39,220 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:39,221 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:39,224 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:39,226 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:49,243 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:49,243 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:49,246 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:49,247 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:59,266 TaurusTrendsSet.sys/tg_test/1/long64_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:59,269 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
MainThread     DEBUG    2017-12-14 13:03:59,272 TaurusTrendsSet.sys/tg_test/1/long_scalar: Dropping event. Reason Error event
Dummy-1        DEBUG    2017-12-14 13:03:59,273 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
MTraceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
IOError: [Errno 0] Error
Logged from file taurusplot.py, line 1873
Dummy-1        DEBUG    2017-12-14 13:04:09,289 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long64_scalar: Unknown unit "No unit (will be treated as unitless)"
Dummy-1        DEBUG    2017-12-14 13:04:11,365 vm-75081.lal.in2p3.fr:20000.sys/tg_test/1.long_scalar: Unknown unit "No unit (will be treated as unitless)"
```

**Comment by cpascual** [comment]
Hi @PhilLAL I was checking the code again, and I suspect that there is some misunderstanding...

The traces that you are showing show messages from a TaurusTrendSet, while in [the code that you linked](https://owncloud.lal.in2p3.fr/index.php/s/FUjheZEqfcVS1Fq/download) (which corresponds to your description of the issue) you are not using a TaurusTRend at all.

Moreover, the linked code file is called `BoutonCommandeTANGO.py`, while you seem to be launching something called `graphiqueTendance.py` Are you sure that you are launching what you think you are launching?

**Comment by PhilLAL** [comment]
I am sorry, you're absolutly right : I got confused with https://owncloud.lal.in2p3.fr/index.php/s/618qs4TkOi1hfWa/download which include a TaurusTrend and has the same behaviour.

**Comment by cpascual** [comment]
Hi, 
I just tried graphiqueTendance.py on a Win7 and it worked without errors (I used the latest latest develop version of taurus, but I do not think that it matters with respect to the 4.1.1release).

I suspect that your issues may be due to some problem for PyTango to access the attributes (is there a firewall between your DS and your client?)

**Comment by PhilLAL** [comment]
I do not have a Win10 and the only computer we have  with it is used for development but this is not anymore a blocking point since we used a walkthrough by installing a Linux Subsystem on Win10.
Even so, we will try to make these test to help increase Win10 support after holidays.
Thank you for the time you took on this.
