### ISSUE TITLE
Taurus Attribute Errors do not print the model name

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#718]
The model name does not appear in the exception traceback printed for exceptions in TangoAttribute calls, it makes very difficult to identify the root cause of the exception.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/base/taurusbase.py", line 359, in filterEvent
    self.handleEvent(*evt)
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/base/taurusbase.py", line 1506, in handleEvent
    self.setToolTip(self.getFormatedToolTip())
  File "/usr/lib/python2.7/dist-packages/taurus/qt/qtgui/base/taurusbase.py", line 663, in getFormatedToolTip
    obj = self.modelObj.getDisplayDescrObj()
  File "/usr/lib/python2.7/dist-packages/taurus/core/tango/tangodevice.py", line 182, in getDisplayDescrObj
    tg_state = self.stateObj.read(cache).rvalue.name
  File "/usr/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py", line 531, in read
    raise self.__attr_err
PyTango.DevFailed: DevFailed[
DevError[
    desc = The polling thread is late and discard this object polling.
           Advice: Tune device server polling
  origin = PollThread::err_out_of_sync
  reason = API_PollThreadOutOfSync
severity = ERR]
]
```

**Comment by cmft** [comment]
I check the code of the TangoAttribute and there are debug message that provide this info. You only have to enable it. Is it not enough? 

To test (with a stopped ds).
```
import taurus
attr_name = 'tango://pc253:10000/motor/motctrl02/3/position'
attr = taurus.Attribute(attr_name)
taurus.setLogLevel(taurus.Debug)
attr.read()

MainThread     DEBUG    2018-08-31 16:51:06,429 pc253.cells.es:10000.mot07.position: [Tango] read failed (API_DeviceNotExported): Device motor/motctrl02/3 is not exported (hint: try starting the device server)
---------------------------------------------------------------------------
ConnectionFailed                          Traceback (most recent call last)
<ipython-input-4-65ed28b4dc5b> in <module>()
----> 1 att.read()

/home/cfalcon/tools/taurus.git/lib/taurus/core/tango/tangoattribute.py in read(self, cache)
    537                     self.debug("[Tango] read failed (%s): %s",
    538                                err.reason, err.desc)
--> 539                     raise df
    540                 except Exception as e:
    541                     self.__attr_value = None

ConnectionFailed: DevFailed[
DevError[
    desc = Device motor/motctrl02/3 is not exported (hint: try starting the device server)
  origin = DeviceProxy::get_corba_name()
  reason = API_DeviceNotExported
severity = ERR]

DevError[
    desc = Failed to read_attribute on device motor/motctrl02/3, attribute position
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]


```

**Comment by sergirubio** [comment]
ok, merci
