### ISSUE TITLE
Segmentation faul in taurusform after drag and drop

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#733]
I have  a seg. fault when drag and drop the same attribute in a taurusform.
I can reproduce it with `sys/tg_test/1/float_scalar` attribute. I'm using Debian 9 with 
- patched Tango package
- the TangoTest and the TangoDB is running in my machine
- taurus from develop branch
 
I attached the core profile:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/python /usr/local/bin/taurusform sys/tg_test/1/float_scalar'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa5e5891a1d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
[Current thread is 1 (Thread 0x7fa5ef8d6700 (LWP 13407))]
(gdb) bt
#0  0x00007fa5e5891a1d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#1  0x00007fa5e58be703 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007fa5e54397f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fa5e5439a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fa5e5439b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fa5e58be854 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007fa5e3cac5d6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007fa5e588c7ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#8  0x00007fa5e588cb55 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007fa5e5892bd9 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#10 0x00007fa5e4c87bdb in ?? () from /usr/lib/python2.7/dist-packages/PyQt4/QtGui.x86_64-linux-gnu.so
#11 0x00005556fb163fda in PyEval_EvalFrameEx ()
#12 0x00005556fb15fd45 in PyEval_EvalCodeEx ()
#13 0x00005556fb167f15 in PyEval_EvalFrameEx ()
#14 0x00005556fb16742f in PyEval_EvalFrameEx ()
#15 0x00005556fb15fd45 in PyEval_EvalCodeEx ()
#16 0x00005556fb15fb09 in PyEval_EvalCode ()
#17 0x00005556fb19014f in ?? ()
#18 0x00005556fb18afc2 in PyRun_FileExFlags ()
#19 0x00005556fb18ab0e in PyRun_SimpleFileExFlags ()
#20 0x00005556fb13baa1 in Py_Main ()
#21 0x00007fa5ee8142e1 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#22 0x00005556fb13b2ca in _start ()

```

**Comment by cpascual** [comment]
Hi @cmft  : Is this 100% reproducible in your environment?

I could not reproduce it (I drag-and-dropped the same attr a dozen times into the same form and it didn't crash).

My environment differ from the one that you described in that I use the stock debian9 Tango package and that I am using a Tango DB on another machine (which is Tango 7, by the way)
