### ISSUE TITLE
TaurusForm: Cannot handle model "...". Using default widget.

### ISSUE THREAD

**Issue by almarass** [taurus-org/taurus#742]
Hi,
I tried the following code to visualize state, status and the attribute 'dishmode' belonging to a running device server:

import sys
from taurus.qt.qtgui.panel import TaurusForm
from taurus.qt.qtgui.application import TaurusApplication

app = TaurusApplication(sys.argv)

attrs = [ 'state', 'status', 'dishmode' ]
model = [ 'tango://151.97.17.82:10000/mid_dish_0001/elt/master/%s' % attr for attr in attrs ]

w = TaurusForm()
w.model = model
w.show()
sys.exit(app.exec_())
-----------------------------------
I got a form together with the following messages:
MainThread     INFO     2018-04-18 19:22:03,884 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-04-18 19:22:07,177 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/)
Exception Exception: Exception('TangoAttribute does not have the attribute _TangoAttribute__cfg_evt_id',) in <bound method TangoAttribute.__del__ of TangoAttribute(tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode)> ignored
MainThread     WARNING  2018-04-18 19:22:18,497 TaurusForm: Cannot handle model "tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode". Using default widget.
Exception Exception: Exception('TangoAttribute does not have the attribute _TangoAttribute__cfg_evt_id',) in <bound method TangoAttribute.__del__ of TangoAttribute(tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode)> ignored

Apparently it is not able to handle properly dishmode attribute (data format scalar, datatype DevEnum)
I installed Taurus 4.3.1.

Any idea?
thanks

**Comment by cmft** [comment]
Hi @almarass ,
Your example works to me. But my five cents is that Taurus can not resolve the IP address in your PC (to get the FQDN); 
Can you copy the output of this snippet:

```
import taurus
a = taurus.Attribute('tango://151.97.17.82:10000/mid_dish_0001/elt/master/state')
print a.getFullName()
```

**Comment by almarass** [comment]
The output is:
tango://151.97.17.82:10000/mid_dish_0001/elt/master/state

**Comment by cmft** [comment]
Hi @almarass ,
Another question, Can you read the attribute with PyTango?

**Comment by cmft** [comment]
I could reproduce the error. The IP is not the problem; Unfortunately Taurus is not ready to manage DevEnum type. I will work on that.

**Comment by almarass** [comment]
The command:
taurusform tango://151.97.17.82:10000/mid_dish_0001/elt/master
gives the messages contained in the file taurusform1.txt (enclosed)
[taurusform1.txt](https://github.com/taurus-org/taurus/files/1927503/taurusform1.txt)
The resulting form shows a lot of void attributes and no commands at all.

I tried the same command using Taurus 3.7.0 and it seems to behave much better.

**Comment by cmft** [comment]
Hi @almarass,
I have been working to support enum in Taurus.
We need to evaluate the current solution and discuss if we integrate it or we wait for a PyTango solution. In the meantime you could try with this [branch](https://github.com/cmft/taurus/tree/enum)

**Comment by almarass** [comment]
The branch does not seem to work (see also attached generated):

taurusform tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode
MainThread     INFO     2018-04-30 11:42:27,775 TaurusRootLogger: Using
"PyQt4" for Qt
MainThread     INFO     2018-04-30 11:42:31,104 taurus.qt.qtgui.icon.icon:
Setting Tango icon theme (from /usr/local/lib/python2.7/dist-
packages/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-04-30 11:42:40,037 TaurusForm: Cannot handle
model "tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode". Using
default widget.

thanks


2018-04-27 11:02 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cmft** [comment]
Hi @almarass,
It seems to be other problem. Can you provide me the debug info? Run `taurusform tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode --taurus-log-level=DEBUG` or share your DS.

It works to me with this [dummy ds](https://gist.github.com/cmft/0419be729514088b0858d3bebaa70227). Can you try with it?

**Comment by almarass** [comment]
Here follow the messages generated by:
taurusform tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode
--taurus-log-level=DEBUG

MainThread     INFO     2018-05-02 19:26:07,334 TaurusRootLogger: Using
"PyQt4" for Qt
MainThread     INFO     2018-05-02 19:26:10,173 taurus.qt.qtgui.icon.icon:
Setting Tango icon theme (from
/usr/local/lib/python2.7/dist-packages/taurus/qt/qtgui/icon/)
MainThread     DEBUG    2018-05-02 19:26:11,110 TaurusManager.TaurusTP:
Starting TaurusTP.W001
MainThread     DEBUG    2018-05-02 19:26:11,116 TaurusManager.TaurusTP:
Starting TaurusTP.W002
MainThread     DEBUG    2018-05-02 19:26:11,117 TaurusManager.TaurusTP:
Starting TaurusTP.W003
MainThread     DEBUG    2018-05-02 19:26:11,118 TaurusManager.TaurusTP:
Starting TaurusTP.W004
MainThread     DEBUG    2018-05-02 19:26:11,119 TaurusManager.TaurusTP:
Starting TaurusTP.W005
MainThread     DEBUG    2018-05-02 19:26:11,413 TaurusManager: Found plugin
TangoFactory
MainThread     DEBUG    2018-05-02 19:26:11,418 TaurusManager: Found plugin
EvaluationFactory
MainThread     DEBUG    2018-05-02 19:26:11,420 TaurusRootLogger: cannot
import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2018-05-02 19:26:11,421 TaurusRootLogger: cannot
import epics module. Taurus will not support the "epics" scheme
MainThread     DEBUG    2018-05-02 19:26:11,421 TaurusManager: Failed to
inspect taurus.core.epics
MainThread     DEBUG    2018-05-02 19:26:11,422 TaurusManager: Details:
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/taurusmanager.py", line
343, in _get_plugin_classes
    globals(), locals(), ['*'])
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/epics/__init__.py",
line 70, in <module>
    from epicsfactory import *
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/epics/epicsfactory.py",
line 34, in <module>
    import epics
ImportError: No module named epics
MainThread     DEBUG    2018-05-02 19:26:11,424 TaurusManager: Found plugin
ResourcesFactory
MainThread     DEBUG    2018-05-02 19:26:13,489 TangoFactory: Error
creating attribute tango://
151.97.17.82:10000/mid_dish_0001/elt/master/dishmode
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangofactory.py",
line 394, in getAttribute
    attr = attr_klass(full_attr_name, dev, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py",
line 289, in __init__
    self._decodeAttrInfoEx(attr_info)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py",
line 972, in _decodeAttrInfoEx
    self.type = data_type_from_tango(i.data_type)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/util/tango_taurus.py",
line 140, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29
MainThread     WARNING  2018-05-02 19:26:13,497 TaurusForm: Cannot handle
model "tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishmode". Using
default widget.
MainThread     DEBUG    2018-05-02 19:26:15,058 TangoFactory: Error
creating attribute tango://
151.97.17.82:10000/mid_dish_0001/elt/master/dishmode
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangofactory.py",
line 394, in getAttribute
    attr = attr_klass(full_attr_name, dev, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py",
line 289, in __init__
    self._decodeAttrInfoEx(attr_info)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/tangoattribute.py",
line 972, in _decodeAttrInfoEx
    self.type = data_type_from_tango(i.data_type)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/util/tango_taurus.py",
line 140, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29
MainThread     DEBUG    2018-05-02 19:26:15,061 TaurusValue: Exception
occured while trying to attach 'tango://
151.97.17.82:10000/mid_dish_0001/elt/master/dishmode'


2018-05-02 8:38 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cmft** [comment]
Ok, the error comes form here:
> line 140, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29

Are you sure that you are using the branch?

Lets check with this code:
```
import taurus
import PyTango

from taurus.core.taurusbasetypes import DataType
from taurus.core.tango.util.tango_taurus import data_type_from_tango


print DataType.keys()
# Expected output ['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Enum', 'Integer', 'DevEncoded']

# Replace it with your ds and attr name
devname = 'testds/test/1'
attrname = 'enum_scalar'
model = devname + '/' + attrname

pdev = PyTango.DeviceProxy(devname)
ptype = pdev.get_attribute_config(attrname).data_type
print ptype
# Expected output 29
ttype = data_type_from_tango(ptype)
print ttype
# Expected output 8
tattr = taurus.Attribute(model)
print tattr.getType(), tattr.getType() == ttype
# Expected output 8 True
```

**Comment by almarass** [comment]
I checked the installed PyTango and Taurus releases:
PyTango.Release.version 9.2.1
taurus.Release.version 4.2.1-alpha

The code gives the following output:

['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Integer',
'DevEncoded']
29
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    ttype = data_type_from_tango(ptype)
  File
"/usr/local/lib/python2.7/dist-packages/taurus/core/tango/util/tango_taurus.py",
line 140, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29


2018-05-03 8:43 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cmft** [comment]
Seems to be problem with your taurus installation (be sure that you are using the `enum` branch of my fork). 

The output of `DataType.keys()` is different:

```
# Expected output ['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Enum', 'Integer', 'DevEncoded']
# Your output
['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Integer', 'DevEncoded']
```
I tested the branch in a clean docker and it works.

**Comment by almarass** [comment]
I downloaded the branch enum from:
https://github.com/cmft/taurus/tree/enum
and installed it

2018-05-03 12:10 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by almarass** [comment]
I used your commands sequence.
Now I get the following PyTango and Taurus versions:
9.2.1
4.3.2-alpha

The execution of the code you sent gives:
['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Enum',
'Integer', 'DevEncoded']
29
8
8 True

If I perform:
taurusform //151.97.17.82:10000/mid_dish_0001/elt/master/dishMode

I get the following messages:

MainThread     INFO     2018-05-03 17:03:56,310 TaurusRootLogger: Using
"PyQt4" for Qt
MainThread     INFO     2018-05-03 17:04:01,571 taurus.qt.qtgui.icon.icon:
Setting Tango icon theme (from
/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/qt/qtgui/icon/)
push_event generated the following python exception:
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/util/event.py",
line 122, in __call__
    return func(obj, *args, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 800, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 826, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 433, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 138, in __init__
    idwv = int(enum_members.get(wvalue, wvalue))
TypeError: int() argument must be a string or a number, not 'NoneType'



2018-05-03 16:40 GMT+02:00 Alessandro Marassi <alessandro.marassi@inaf.it>:

**Comment by cmft** [comment]
Hi @almarass ,
I found a bug in the decode of read only DevEnum attribute. I fixed and pushed a new commit in this branch. I hope this solve your problem.

**Comment by almarass** [comment]
Hi,
I tried again with a single enum attribute:
taurusform //151.97.17.82:10000/mid_dish_0001/elt/master/dishMode
It works.

Then I tried with a whole device server:
taurusform //151.97.17.82:10000/mid_dish_0001/elt/master
and, after clicking "show device" button, I got the following messages:

MainThread     INFO     2018-05-04 10:16:33,410 TaurusRootLogger: Using
"PyQt4" for Qt
MainThread     INFO     2018-05-04 10:16:33,689 taurus.qt.qtgui.icon.icon:
Setting Tango icon theme (from
/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-05-04 10:16:57,134 TaurusRootLogger:
/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/qt/qtgui/util/tauruswidgetfactory.py:111:
DeprecationWarning: TaurusConsole is deprecated since 4.0.4. Use
silx.gui.console.IPythonWidget instead
  m = __import__(module_name, fromlist=['*'], level=0)

MainThread     WARNING  2018-05-04 10:16:59,804 TaurusRootLogger:
/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/qt/qtgui/base/tauruscontroller.py:83:
DeprecationWarning: _get_value is deprecated since 4.0. Use .rvalue instead
  return getattr(valueObj, "value", None)

push_event generated the following python exception:
Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/util/event.py",
line 122, in __call__
    return func(obj, *args, **kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 800, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 826, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 433, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File
"/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/core/tango/tangoattribute.py",
line 141, in __init__
    wvalue = enum_members.values()[idwv]
IndexError: list index out of range


2018-05-04 9:03 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cmft** [comment]
Sorry @almarass, I can not reproduce the error. Can you try to reproduce the error with my [DS](https://gist.github.com/cmft/0419be729514088b0858d3bebaa70227)?

**Comment by cmft** [comment]
I could not see your attachment. is it working? The pooling warnings are nor normal (seems to be a communication problem) Can you read attribute with PyTango?. I don't see them in my pc.    
```
TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more
```

**Comment by almarass** [comment]
Apparently it works.
I am afraid that the real device server I tried to interface with, has too
many attributes to read by taurusform; this is not the case of your device.

The device server is running in the local machine; I can not imagine any
communication problem.

Maybe I have not properly understood: what don't you see in your pc?
What should I try to read with PyTango?

2018-05-07 8:41 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cpascual** [comment]
Hi @almarass , is this already solved for you?
Can we close the issue?

**Comment by cmft** [comment]
Since PyTango fixed the support of tango enum we should change the current implementation

**Comment by almarass** [comment]
Sorry for the delay in my reply.
I updated taurus from version 4.2.1-alpha to 4.4.1-alpha, while pytango version is always 9.2.1
It seems uncapable to handle devEnum attributes again.
I tried to check the dummy ds https://gist.github.com/cmft/0419be729514088b0858d3bebaa70227 with cmft 3rd May code and it outputs:
['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Integer', 'DevEncoded']
29
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    ttype = data_type_from_tango(ptype)
  File "/home/tango-cs/Downloads/taurus/lib/taurus/core/tango/util/tango_taurus.py", line 141, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29

thanks,
Alex

**Comment by cmft** [comment]
Hi @almarass ,
It was not integrated since the implementation did not use the PyTango API. PyTango v9.2.4 fixed the troubles with devEnum, so the solution should be base on this version. For that reason we decide to drop this PR from Jul18 release.  Sorry for the inconvenience.

**Comment by almarass** [comment]
Hi Carlos,
using PyTango 9.2.4 and Taurus 4.4.0, while testing  the dummy ds
https://gist.github.com/cmft/0419be729514088b0858d3bebaa70227 with cmft 3rd
May code, I got:

['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Integer',
'DevEncoded']
29
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    ttype = data_type_from_tango(ptype)
  File "/usr/local/lib/python2.7/dist-packages/taurus/core/tango/util/tango_taurus.py",
line 141, in data_type_from_tango
    return FROM_TANGO_TO_TAURUS_TYPE[data_type]
KeyError: 29

Then, after having reinstalled Taurus 4.3.2-alpha, I got:

['Object', 'String', 'Float', 'Bytes', 'DevState', 'Boolean', 'Enum',
'Integer', 'DevEncoded']
29
8
8 True

which is apparently correct.

My original problem was the impossibility to get enum values out of a Tango
device server attribute (dishMode in this case).
When running: taurusform {tango://
151.97.17.82:10000/mid_dish_0001/elt/master/dishMode}
I got:

MainThread     INFO     2018-09-08 08:51:43,452 TaurusRootLogger: Using
"PyQt4" for Qt
MainThread     INFO     2018-09-08 08:51:43,848 taurus.qt.qtgui.icon.icon:
Setting Tango icon theme (from
/usr/local/lib/python2.7/dist-packages/taurus-4.3.2a0-py2.7.egg/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-09-08 08:51:45,172 TaurusForm: Cannot handle
model "{tango://151.97.17.82:10000/mid_dish_0001/elt/master/dishMode}".
Using default widget.
MainThread     WARNING  2018-09-08 08:51:45,187 TaurusForm: an error
occurred while adding the child "{tango://
151.97.17.82:10000/mid_dish_0001/elt/master/dishMode}". Skipping

and the attached window.

When using the same command before having installed Taurus 4.4.0 I got a
correct window showing enum values.

I am suspecting that different Taurus versions install and uninstall
operations are not clean.

Any idea?

Thanks,
Alex

2018-09-07 10:35 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cpascual** [comment]
> I am suspecting that different Taurus versions install and uninstall operations are not clean. Any idea?

I would be surprised if it was the case, but I cannot rule it out. In order to check it, you could try to reproduce the problem by repeating the install sequence with virtualenv

Another thing to watch for is the possibility, depending on the installation method, of taurus **dependencies** being (automatically) updated.
