### ISSUE TITLE
DevErrors when showing sys/database/2 with taurusdevicepanel

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#774]
this may be something related to my setup, and anyway it does not seem to cause other problems, so I am not giving it priority... but I  report it here to keep it documented.

To reproduce: run `taurusdevicepanel sys/database/2` and wait for ~10s

A buch of tracebacks like this one are dumped into the console:

```
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 359, in filterEvent
    self.handleEvent(*evt)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 1506, in handleEvent
    self.setToolTip(self.getFormatedToolTip())
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 663, in getFormatedToolTip
    obj = self.modelObj.getDisplayDescrObj()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangodevice.py", line 182, in getDisplayDescrObj
    tg_state = self.stateObj.read(cache).rvalue.name
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tango/tangoattribute.py", line 538, in read
    raise self.__attr_err
PyTango.DevFailed: DevFailed[
DevError[
    desc = Event channel is not responding anymore, maybe the server or event system is down
  origin = EventConsumer::KeepAliveThread()
  reason = API_EventTimeout
severity = ERR]
]
```

**Comment by teresanunez** [comment]
I have just tried it (in debian9) and I do not get the tracebacks.

**Comment by cmft** [comment]
I did some test using a debian 9 setup: 
- When the db is on Tango9 everything works.
- But when I tied with a Tango7 device (controls01) I had this error:
```
Traceback (most recent call last):
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/base/taurusbase.py", line 358, in filterEvent
    self.handleEvent(*evt)
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/base/taurusbase.py", line 1515, in handleEvent
    self.setToolTip(self.getFormatedToolTip())
  File "/home/cfalcon/tools/taurus.git/lib/taurus/qt/qtgui/base/taurusbase.py", line 662, in getFormatedToolTip
    obj = self.modelObj.getDisplayDescrObj()
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/tango/tangodevice.py", line 182, in getDisplayDescrObj
    tg_state = self.stateObj.read(cache).rvalue.name
  File "/home/cfalcon/tools/taurus.git/lib/taurus/core/tango/tangoattribute.py", line 550, in read
    raise self.__attr_err
PyTango.DevFailed: DevFailed[
DevError[
    desc = tango://controls01.cells.es:10000/dserver/DataBaseds/2 has no event channel defined in the database
           Maybe the server is not running or is not linked with Tango release 4.x (or above)... 
  origin = NotifdEventConsumer::connect_event_channel
  reason = API_NotificationServiceFailed
severity = ERR]
]
```
- And I have the same error when the db is on Tango8 (controls02)
