### ISSUE TITLE
Jul18 manual release tests: win10

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#790]
This issue is created for reporting the results of the manual tests for Jul18 release on windows 10

They are also considered for the release PR: #784

### Installation
- [x] Install Taurus from the [msi](https://ci.appveyor.com/api/buildjobs/j6vijm6oq90wbei1/artifacts/dist%2Ftaurus-4.4.0a0.win32.msi)

### Taurusdemo

- [x] Test all of the buttons of the taurusdemo. All demos should launch correctly and without raising exceptions
- [x] For TaurusLabel, check foreground role, the background role, the prefix, the suffix, the formatter, etc.
- [x] For TaurusLabel, in order to test the background role=value, you can use the following attribute: `eval:["FAULT","ON","OFF","ALARM"][randint(4)]`
- [x] For TaurusLabel, use a model with fragment (e.g., `sys/tg_test/1/ampli#rvalue.magnitude`, `eval:Q('1mm')#rvalue.unit"`, `eval:10*arange(9)#rvalue[3:4]`)
- [x] For LCD: Test the foreground roles and the background role
- [x] For Led: Test the colors, ON color, Off color.

### taurusplot
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurusplot "eval:Q(rand(333),'mm')" sys/tg_test/1/wave`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [x] Test plot configuration dialog
- [x] Test changing curve titles
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurustrend
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Execute: `taurustrend "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Execute: `taurustrend -xe "eval:Q(rand(),'mm')" sys/tg_test/1/ampli`
- [x] Check region Zoom in and out with region zoom and go back stacked zoom levels with
- [x] Check mouse wheel Zoom
- [x] Test panning (dragging with CTRL pressed)
- [x] Test inspector mode
- [x] Test pause mode
- [x] Move curves between axes by clicking on legend (and test zoom on Y2)
- [ ] Test plot configuration dialog
- [x] Test Forced reading mode
- [x] Test Save & restore config (change curve properties, zoom, etc & check that everything is restored)
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### Test taurusimage

- [x] Execute `taurusimage --demo`
- [x] try to resize the image and move it using the mouse.

### taurustrend2d

- [x] Execute: `taurustrend2d --demo --taurus-polling-period 333`
- [x] Execute: `taurustrend2d -xt --demo --taurus-polling-period 333`  **(known to fail in 4.1.0)** - **"FAILS"**
- [x] Execute: `taurustrend2d -xe --demo --taurus-polling-period 333`
- [x] Test auto-scroll and auto-scale tools
- [ ] Test Save & restore config (change axes range, zoom, tool status colormap etc & check that everything is restored)

### Tauruscurve & taurustrend1d
(unused and to be deprecated, you may test but **do not worry too much if they fail**)

- [ ] Execute: `tauruscurve --demo`
- [ ] Change size
- [ ] Move curve with mouse
- [ ] Resize curve with mouse
- [ ] Test some option of the menu with mouse.
- [ ] Execute: `taurustrend1d "eval:Q(rand(),'mm')"` and test it in the same way

### taurusdesigner
- [x] Check that taurusdesigner is correctly opened and taurus widgets are present in the catalog
- [x] Create an empty widget and drag various taurus widgets to it (they should be correctly dropped)

### taurusdevicepanel
- [x] Execute: `taurusdevicepanel sys/tg_test/1`
- [x] Check that it opens correctly and that the attrs and commands are populated
- [x] Execute SwitchStates command (see that the state label changes to FAULT and its color to red)
      and then execute the Init command and the label returns to RUNNING (blue)

### tauruspanel
- [x] Execute: `tauruspanel`
- [x] Navigate in the tree and select the TangoTest device (the attr an command panels should be populated)

### taurusform
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusform sys/tg_test/1/short_scalar`
- [x] Test to drag and drop of this attribute onto the same form many times (4 times)
      (If it crashes, you are seeing bug #96) - **STILL CRASHING**
- [x] Open "Modify Contents" and add sys/tg_test/1 and all of its attributes. They should all show ok
- [x] Test the compact mode  (switch to compact, noncompact; edit when in compact mode, ...) for a single
      value (from the context menu of a value label)
- [x] Test compact mode for all values (from the context menu of the whole form)
- [x] Test changing labels
- [x] Test changing the formatter for a single value (from the context menu of a value label) (use, e.g. `>>{}<<`)
- [x] Test changing the formatter for all values (from the context menu of the whole form)
- [x] Test re-order of values with "Modify contents"
- [x] Test the different "show" buttons (tables, images, spectra)
- [x] Change the write widget of double_scalar by a TaurusWheelEdit
- [x] Change other read and write widgets
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusgui
(basically try all features described in the [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

- [x] Launch `taurusgui example01`
- [x] Test (un)lock view
- [x] Create a new panel (a TaurusForm) and drag and drop several models from other forms
- [x] Move panels around (with view unlocked!) and hide ("close") and re-show them
- [x] Test saving and restoring perspectives
- [x] Test drag&drop from a form to a trend
- [x] Test clicking on "example01 synoptic" elements and check that the panels raised
- [x] Test that selecting a panel changes the selection on "example01 synoptic"
- [x] Test the actions in the menus
- [x] Create a new TaurusGui (call it `foogui`) with `taurusgui --new-gui` (follow the wizard)
- [x] Install `foogui` with pip (using a virtualenv may be a good idea)
- [x] launch `foogui` using the script that has been installed
- [ ] ... other features from [user's guide](http://taurus-scada.org/en/latest/users/ui/index.html)

### taurusconfigbrowser
- [x] Open an ini file with taurusconfigbrowser and check that it is loaded correctly.

**Comment**
* Not able to open configuration file:

```
C:\Users\IEUser>taurusconfigbrowser C:\Users\IEUser\AppData\Roaming\ALBA\test.ini
MainThread     INFO     2018-07-26 17:50:21,483 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-07-26 17:50:21,640 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from C:\Python27\lib\site-packages\taurus\qt\qtgui\icon\)
Traceback (most recent call last):
  File "C:\Python27\Scripts\taurusconfigbrowser-script.py", line 11, in <module>
    load_entry_point('taurus==4.4.0a0', 'console_scripts', 'taurusconfigbrowser')()
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\panel\taurusconfigeditor.py", line 508, in main
    w.loadFile(args[0])
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\panel\taurusconfigeditor.py", line 472, in loadFile
    self.tree.loadFile(iniFileName)
  File "C:\Python27\lib\site-packages\taurus\qt\qtgui\panel\taurusconfigeditor.py", line 84, in loadFile
    shutil.copyfile(self.originalFile, self._temporaryFile)
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'c:\\users\\ieuser\\appdata\\local\\temp\\tmp3ljnyh'
```

### taurusiconcatalog
- [x] Launch `taurusiconcatalog`. Several tabs with an array of icons [should be displayed](http://taurus-scada.org/en/latest/devel/icon_guide.html#taurus-icon-catalog)
- [x] Check that tooltips give info on each icon
- [x] Click on some icons and check that they give a bigger view of the icon and more info.

**General Comments**:
* On window closing python crashed: `Assertion failed: Successful WSASTARTUP not yet performed (..\..\..\src\signaler.cpp:377)`

**Comment by reszelaz** [comment]
No release critical bugs.

**Comment by reszelaz** [comment]
**General Comment**

On window closing python crashed: `Assertion failed: Successful WSASTARTUP not yet performed (..\..\..\src\signaler.cpp:377)`

Something similar was observed in the last release #709.
