### ISSUE TITLE
Taurusgui one instance protection could advice on how to clean previously crashed instance

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#806]
At Alba our GUIs crash from time to time. These leave a socket file protecting another instance to be started. Recovering from this situation requires deletion of the socket file e.g. `/tmp/__socket_zreszela-MacroGUI__`.

We could add some information to the currently showed pop-up, which says: "Only one istance of MacroGUI is allowed to run the same time" with possible causes of this situation and some expert instructions on how to delete the problematic file.

**Comment by cpascual** [comment]
If i am not mistaken, such instructions are logged, but only in the console.

Anyway, when we designed the feature we considered that manually removing the lock file was potentially too dangerous if done by non-experts (risk of configurations being lost if done without properly checking that no other process for the same GUI is running) and therefore we decided not to make that solution too obvious.
This is just to explain that the current situation was fruit of a conscious design choice... but of course it could be reevaluated.

**Comment by reszelaz** [comment]
Just to complete the idea of logging into the console output I paste the information that is logged as on today:

```
zreszela@pc255:~> taurusgui macrogui --taurus-log-level=trace
MainThread     INFO     2018-09-12 10:10:45,214 TaurusRootLogger: Using "PyQt4" for Qt                                                                                             
MainThread     INFO     2018-09-12 10:10:45,389 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/zreszela/workspace/taurus/lib/taurus/qt/qtgui/icon/)               
MainThread     INFO     2018-09-12 10:10:45,598 TaurusRootLogger: Starting execution of TaurusGui                                                                                  
MainThread     TRACE    2018-09-12 10:10:45,628 TaurusManager: reInit()                                                                                                            
MainThread     DEBUG    2018-09-12 10:10:45,628 TaurusManager.TaurusTP: Starting TaurusTP.W001                                                                                     
MainThread     DEBUG    2018-09-12 10:10:45,628 TaurusManager.TaurusTP: Starting TaurusTP.W002                                                                                     
MainThread     DEBUG    2018-09-12 10:10:45,629 TaurusManager.TaurusTP: Starting TaurusTP.W003                                                                                     
MainThread     DEBUG    2018-09-12 10:10:45,629 TaurusManager.TaurusTP: Starting TaurusTP.W004                                                                                     
MainThread     DEBUG    2018-09-12 10:10:45,629 TaurusManager.TaurusTP: Starting TaurusTP.W005                                                                                     
MainThread     DEBUG    2018-09-12 10:10:45,629 TaurusManager.TaurusTSP: Starting TaurusTSP.W001                                                                                   
MainThread     DEBUG    2018-09-12 10:10:45,654 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme                                           
MainThread     DEBUG    2018-09-12 10:10:45,655 TaurusRootLogger: cannot import epics module. Taurus will not support the "epics" scheme                                           
MainThread     DEBUG    2018-09-12 10:10:45,655 TaurusManager: Failed to inspect taurus.core.epics                                                                                 
MainThread     DEBUG    2018-09-12 10:10:45,656 TaurusManager: Details:                                                                                                            
Traceback (most recent call last):                                                                                                                                                 
  File "/home/zreszela/workspace/taurus/lib/taurus/core/taurusmanager.py", line 377, in _get_plugin_classes                                                                        
    globals(), locals(), ['*'])                                                                                                                                                    
  File "/home/zreszela/workspace/taurus/lib/taurus/core/epics/__init__.py", line 70, in <module>                                                                                   
    from epicsfactory import *                                                                                                                                                     
  File "/home/zreszela/workspace/taurus/lib/taurus/core/epics/epicsfactory.py", line 34, in <module>                                                                               
    import epics                                                                                                                                                                   
ImportError: No module named epics                                                                                                                                                 
MainThread     DEBUG    2018-09-12 10:10:45,661 TaurusManager: Found plugin EvaluationFactory                                                                                      
MainThread     DEBUG    2018-09-12 10:10:45,662 TaurusManager: Found plugin ResourcesFactory                                                                                       
MainThread     DEBUG    2018-09-12 10:10:45,662 TaurusManager: Found plugin TangoFactory                                                                                           
MainThread     INFO     2018-09-12 10:10:45,800 TaurusApplication: Logs will be saved in /home/zreszela/tmp/MacroGUI/MacroGUI.log                                                  
MainThread     INFO     2018-09-12 10:10:45,801 TaurusGui: Another application with key "__socket_zreszela-MacroGUI__" is already running
MainThread     ERROR    2018-09-12 10:10:45,802 TaurusGui: Only one istance of MacroGUI is allowed to run the same time
Dummy-1        TRACE    2018-09-12 10:10:47,109 TangoFactory: [TangoFactory] cleanUp
Dummy-1        TRACE    2018-09-12 10:10:47,110 TaurusManager: cleanUp()
Dummy-1        TRACE    2018-09-12 10:10:47,111 TaurusManager: [TaurusManager] cleanUp
```

**Comment by cpascual** [comment]
>In the first case (already running), the user could fix the issue by simply looking for it in the right monitor/desktop/workspace.

The problem is that in some environments (as in our case) users may log in from different machines with the same login and launch the application remotely, so a casual visual inspection may not reveal the other instance running. A proper check is to look at the process table, etc, which is often "too advanced" for a basic user. 

>In the second case (hang), a first-line-support could identify the process and kill it, 

The recipe of manually deleting the lock file applies to this case. The problem (and the reason we decided not to give the recipe in the pop-up) is that we considered it safer that non-expert users would call "first-line support" instead of removing the lock file themselves. 
Note that the consequences of removing the lock without proper checks can be very serious (loss of configurations of the GUI if the GUI was still running) 

> in the third case (crashed), 

lock files left by crashed processes are almost always automatically removed by the new GUI itself, which already incorporates some checks for this (and logs the lock-file removal). See `TaurusMainWindow.checkSingleInstance()`

**Comment by guifrecuni** [comment]
Ok, then we will make sure that our desktop launchers show-up the terminal to have access to that information that may be used for first-line help on site.
