### ISSUE TITLE
macroexecutor yellow line reports errors 

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#812]
If you try to write a macro using the yellow line of the macroexcutor it reports theses errors
```
Traceback (most recent call last):
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 382, in textChanged
    self.validateAllExpresion()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 284, in validateAllExpresion
    param_info = macro_params_info[counter-1]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 382, in textChanged
    self.validateAllExpresion()
  File "/home/cfalcon/tools/sardana-sardana.git/src/sardana/taurus/qt/qtgui/extra_macroexecutor/macroexecutor.py", line 269, in validateAllExpresion
    macro_params_info = macro_obj.getElementInfo(mlist[0]).parameters
AttributeError: 'NoneType' object has no attribute 'parameters'
```

**Comment by cmft** [comment]
The bug seems to be introduce in  the PR [#876](https://github.com/sardana-org/sardana/pull/876)

**Comment by cmft** [comment]
Moved to sardana project
