### ISSUE TITLE
ThreadPool not able to report traceback

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#834]
One can use the following snippet to reproduce the problem:
```python
import time
from taurus.core.util.threadpool import ThreadPool

pool = ThreadPool()

def job():
    1/0

pool.add(job)
time.sleep(1)
```
In support-3.x:
```
ThreadPool.W001 ERROR    2018-12-18 16:46:14,679 ThreadPool.ThreadPool.W001: Uncaught exception running job 'job' called from thread MainThread:
  File "/home/zreszela/.PyCharm2018.2/config/scratches/scratch_2.py", line 9, in <module>
    pool.add(job)
Traceback (most recent call last):
  File "/home/zreszela/workspace/taurus/lib/taurus/core/util/threadpool.py", line 134, in run
    cmd(*args, **kw)
  File "/home/zreszela/.PyCharm2018.2/config/scratches/scratch_2.py", line 7, in job
    1/0
ZeroDivisionError: integer division or modulo by zero
```

In develop:
```
ThreadPool.W001 ERROR    2018-12-18 16:47:18,487 ThreadPool.ThreadPool.W001: Uncaught exception running job 'job' called from thread MainThread:
  File "/home/zreszela/.PyCharm2018.2/config/scratches/scratch_2.py", line 9, in <module>
    pool.add(job)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 1277, in _log
    fn, lno, func = self.findCaller()
ValueError: too many values to unpack
```

**Comment by cpascual** [comment]
Hint : the snippet works fine when run in py3

**Comment by cmft** [comment]
I simplified the snippet:
```
from taurus.core.util.log import Logger
from traceback import extract_stack, format_list

l = Logger()

cmd = '1/0'
th_id = id(l)
try:
    1/0
except:
    stack = extract_stack()


orig_stack = "".join(format_list(stack))
l.error("Uncaught exception running job '%s' called "
           "from thread %s:\n%s",
           cmd, th_id, orig_stack, exc_info=1)
```
The error is caused by  the kw `exc_info=1`
