### ISSUE TITLE
h5py import fails after prior import of taurus 

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#836]
I discovered it on the Debian 9 docker container where locale is set to POSIX by default but can be easliy reproduced on a normal Debian 9 system:

```
zreszela@pc255:~/workspace/taurus (develop)> LANG=POSIX python -c "import taurus; import h5py"
/usr/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
945
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/h5py/__init__.py", line 60, in <module>
    from .tests import run_tests
  File "/usr/lib/python2.7/dist-packages/h5py/tests/__init__.py", line 15, in <module>
    from . import old, hl
  File "/usr/lib/python2.7/dist-packages/h5py/tests/old/__init__.py", line 4, in <module>
    from . import ( test_attrs,
  File "/usr/lib/python2.7/dist-packages/h5py/tests/old/test_group.py", line 41, in <module>
    fsencode(u"α")
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/compat.py", line 68, in fsencode
    return filename.encode(encoding, errors)
  File "/usr/lib/python2.7/dist-packages/future/utils/surrogateescape.py", line 59, in surrogateescape_handler
    decoded = replace_surrogate_encode(mystring)
  File "/usr/lib/python2.7/dist-packages/future/utils/surrogateescape.py", line 87, in replace_surrogate_encode
    raise exc
NameError: global name 'exc' is not defined
```

This however works well with support-3.x:

```
zreszela@pc255:~/workspace/taurus (support-3.x)> LANG=POSIX python -c "import taurus; import h5py"
/usr/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.                                       
  from ._conv import register_converters as _register_converters
```

Using the en_US.UTF-8 it works well with the develop branch:

```
zreszela@pc255:~/workspace/taurus (develop)> LANG=en_US.UTF-8 python -c "import taurus; import h5py"                                                                                                                                                                           
/usr/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.                                       
  from ._conv import register_converters as _register_converters
```

For me it looks like a bad coincidence of h5py which want to *skip* tests and a bug in python future module. When I fix the bug in the future module it does not allow me to import h5py after taurus anyway.

So, I think it is worth to take a deeper look on this...

**Comment by reszelaz** [comment]
For the docker container the following should workaround this:

```dockerfile
# Change locale from POSIX to en_US.UTF-8
RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LC_ALL en_US.UTF-8
```

**Comment by cpascual** [comment]
Hi, this is due to a bug in h5py which got fixed in h5py 2.8: 
https://github.com/h5py/h5py/issues/803

In the meanwhile (e.g. if you are using the h5py provided in the official deb from debian-strech) the workaround is (as you already found) to set the locale to UTF-8.
 
**Note that this can be done without needing to build locales:** Just set the env var `LANG` to `C.UTF-8` (which, AFAIK, is already built in most systems)

**Comment by cpascual** [comment]
I am closing this as "rejected" because it is a bug in an external library and it is already fixed in that library.

**Comment by reszelaz** [comment]
Great! thanks a lot!
