### ISSUE TITLE
taurusgui example01 fails to launch with python3

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#870]
Seen both in debian and win10 when using a py3qt5 conda environment

```console
(py3qt5) cpascual@pc218:~$ taurusgui example01
MainThread     INFO     2019-02-15 17:20:46,508 TaurusRootLogger: Using PyQt5 (v5.6 , with Qt 5.6.2)
MainThread     INFO     2019-02-15 17:20:51,879 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
MainThread     INFO     2019-02-15 17:20:54,930 TaurusRootLogger: Starting execution of TaurusGui
MainThread     INFO     2019-02-15 17:20:58,893 TaurusApplication: Logs will be saved in /home/cpascual/tmp/EXAMPLE 01/EXAMPLE 01.log
MainThread     INFO     2019-02-15 17:20:59,016 TaurusGui: Registering as single instance with key "__socket_cpascual-EXAMPLE 01__"
MainThread     ERROR    2019-02-15 17:20:59,476 TaurusGui: Error loading synoptic file "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example01/images/example01.jdw".
Synoptic won't be available
MainThread     INFO     2019-02-15 17:20:59,477 TaurusGui: Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 821, in createMainSynoptic
    from taurus.qt.qtgui.graphic import TaurusJDrawSynopticsView
ImportError: cannot import name 'TaurusJDrawSynopticsView'


        ------------------------------------------------------------
         filename = /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py
         function = createMainSynoptic
             line = [820]: jdwFileName = os.path.join(self._confDirectory, synopticname)
          -> line = [821]: from taurus.qt.qtgui.graphic import TaurusJDrawSynopticsView
             line = [822]: synoptic = TaurusJDrawSynopticsView()
           locals = 
                                 msg = Error loading synoptic file "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/t[...]
                                   e = cannot import name 'TaurusJDrawSynopticsView'
                         jdwFileName = /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example0[...]
                        synopticname = images/example01.jdw
                                self = <taurus.qt.qtgui.taurusgui.taurusgui.TaurusGui object at 0x7f77c2a72558>
MainThread     ERROR    2019-02-15 17:21:06,280 LogExceptHook: Unhandled exception:
Traceback (most recent call last):
  File "/home/cpascual/miniconda/envs/py3qt5/bin/taurusgui", line 11, in <module>
    load_entry_point('taurus', 'console_scripts', 'taurusgui')()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 1654, in main
    configRecursionDepth=configRecursionDepth)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 323, in __init__
    self.loadConfiguration(confname)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 1138, in loadConfiguration
    self.createMainSynoptic(s)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/taurusgui/taurusgui.py", line 836, in createMainSynoptic
    "SelectedInstrument", synoptic, "graphicItemSelected")
UnboundLocalError: local variable 'synoptic' referenced before assignment
Segmentation fault                                                           
```

**Comment by cpascual** [comment]
this was solved long ago, so I am closing.
