### ISSUE TITLE
Can't pickle QIcon objects. 

### ISSUE THREAD

**Issue by asenchenko** [taurus-org/taurus#884]
I can not add Attribute to TaurusForm. Model Chooser reports `Can't pickle QIcon objects`.
ubuntu 18.04, python 3.6,  `TaurusRootLogger: Using PyQt4 (v4.12.1 , with Qt 4.8.7).`
I didn't find an issue or PR for this problem but this problem was  mentioned here https://github.com/taurus-org/taurus/pull/814#issuecomment-458030386.

**Comment by cpascual** [comment]
Confirmed (also with Py3+PyQt5)
To reproduce: 
- launch taurusform
- use the model chooser to select a 'sys/tg_test/1/wave'

```console
Traceback (most recent call last):
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmodellist.py", line 360, in _onDataChanged
    self.dataChangedSignal.emit(self.getModelItems())
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmodellist.py", line 424, in getModelItems
    return self._model.dumpData()
  File "/nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/panel/taurusmodellist.py", line 143, in dumpData
    return copy.deepcopy(self.items)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle QIcon objects
```

But note that it works if the madel is passedon the CLI!:
```
taurusform sys/tg_test/1/wave
```

**Comment by cpascual** [comment]
Note: IMHO this is a bug in some PyQt versions. Note that the following code works in some versions and not other:

```python
from PyQt5 import Qt
import copy, sys
print(sys.version)
a = Qt.QApplication(sys.argv)
copy.deepcopy(QIcon())  # this works on py 2.7.11 and 3.5.3 but raises exception on 3.6.6
```
