### ISSUE TITLE
Issue when start spock with sardana-2.7.1 and taurus-4.5.1

### ISSUE THREAD

**Issue by aureocarneiro** [taurus-org/taurus#907]
At MAX IV we installed the new tango version 9.3.2, sardana 2.7.1, PyTango 9.3.0 and taurus 4.5.1, to test our old devices.
When we start Spock with our old Pool and MacroServer devices we have this error:

Connected to door/ctl/aurfre
push_event generated the following python exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/util/event.py", line 140, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 808, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 836, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 435, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 122, in __init__
    rvalue = p.value
AttributeError: 'DeviceAttribute' object has no attribute 'value'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

push_event generated the following python exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/util/event.py", line 140, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 808, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 836, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 435, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 122, in __init__
    rvalue = p.value
AttributeError: 'DeviceAttribute' object has no attribute 'value'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

push_event generated the following python exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/util/event.py", line 140, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 808, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 836, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 435, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 122, in __init__
    rvalue = p.value
AttributeError: 'DeviceAttribute' object has no attribute 'value'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

push_event generated the following python exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/util/event.py", line 140, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 808, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 836, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 435, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 122, in __init__
    rvalue = p.value
AttributeError: 'DeviceAttribute' object has no attribute 'value'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

push_event generated the following python exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 210, in greener
    return executor.submit(fn, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tango/green.py", line 92, in submit
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/util/event.py", line 140, in __call__
    return func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 808, in push_event
    etype, evalue = self._pushAttrEvent(event)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 836, in _pushAttrEvent
    attr_value = self.decode(event.attr_value)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 435, in decode
    value = TangoAttrValue(pytango_dev_attr=attr_value, attr=self)
  File "/usr/lib/python2.7/site-packages/taurus/core/tango/tangoattribute.py", line 122, in __init__
    rvalue = p.value
AttributeError: 'DeviceAttribute' object has no attribute 'value'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by reszelaz** [comment]
It looks like you hit https://github.com/tango-controls/pytango/issues/271.
I think this is fixed in the PyTango develop branch.

**Comment by aureocarneiro** [comment]
@reszelaz thanks ! Its working!

**Comment by cpascual** [comment]
It is nice to hear that it works now.
Closing as rejected (not a taurus bug)
