### ISSUE TITLE
win10 py3qt5 taurus demo LCD error

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#967]
When performing manual tests for release Jul19, on a taurus-vagrant win10 machine (https://git.cells.es/controls/taurus-vagrant), with conda environment py3qt5.

By deleting character by character the two model names appearing at demo LCD disply at a fast pace, I got this error. Not always reproduced (maybe 50% of times).

<pre>
TimerLoop 1    ERROR    2019-07-25 05:35:23,475 TaurusPollingTimer[3000]: poll_reply error
Exception in thread TimerLoop 1:
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\miniconda\envs\py3qt5\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\util\timer.py", line 91, in __run
    self.__function(*self.__args, **self.__kwargs)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tauruspollingtimer.py", line 136, in _pollAttributes
    for dev, attrs in self.dev_dict.items():
RuntimeError: dictionary changed size during iteration
</pre>

Other error:
By changing the model name, foreground role, etc. the application crashes: not easily reproducible.

**Comment by cpascual** [comment]
I change the title because it can be reproduced also on debian, and using a TaurusLabel, with the following snippet that just does a stress test on setting models:


```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLabel


import sys
app = TaurusApplication(cmd_line_parser=None)

w = TaurusLabel()
w.resize(300,100)
w.show()

def loopmodels(model = 'sys/tg_test/1/double_scalar'):
    for _ in range(100):
        for i in range(len(model), -1, -1):
            print(i, model[:i])
            w.setModel(model[:i])
            app.processEvents()
    w.setModel(model)

loopmodels()

**Comment by cpascual** [comment]
Notes:
- I cannot reproduce it using Py 2
- Using PyQt4 or PyQt5 does not seem to affect

**Comment by cpascual** [comment]
It can also be reproduced with a TaurusWidget instead of a TaurusLabel:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusWidget

app = TaurusApplication(cmd_line_parser=None)

w = TaurusWidget()
w.resize(300,100)

model = 'sys/tg_test/1/'
w.setModel(model)

w.show()

def loopmodels(model = 'sys/tg_test/1/double_scalar'):
    for _ in range(100):
        for i in range(len(model), -1, -1):
            print(i, model[:i])
            w.setModel(model[:i])
            app.processEvents()
    w.setModel(model)

loopmodels()
```

``` console
$ python stress2.py 
MainThread     INFO     2019-07-25 16:15:40,419 TaurusRootLogger: Using PyQt5 (v5.6 with Qt 5.6.2 and Python 3.6.8)
MainThread     INFO     2019-07-25 16:15:40,646 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
MainThread     INFO     2019-07-25 16:15:40,855 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
27 sys/tg_test/1/double_scalar
26 sys/tg_test/1/double_scala
25 sys/tg_test/1/double_scal
24 sys/tg_test/1/double_sca
23 sys/tg_test/1/double_sc
TimerLoop 1    ERROR    2019-07-25 16:15:41,258 TaurusPollingTimer[3000]: poll_reply error
22 sys/tg_test/1/double_s
21 sys/tg_test/1/double_
20 sys/tg_test/1/double
Exception in thread TimerLoop 1:
Traceback (most recent call last):
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/util/timer.py", line 91, in __run
    self.__function(*self.__args, **self.__kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tauruspollingtimer.py", line 136, in _pollAttributes
    for dev, attrs in self.dev_dict.items():
RuntimeError: dictionary changed size during iteration

19 sys/tg_test/1/doubl
18 sys/tg_test/1/doub
17 sys/tg_test/1/dou
16 sys/tg_test/1/do
15 sys/tg_test/1/d
14 sys/tg_test/1/
13 sys/tg_test/1
12 sys/tg_test/
11 sys/tg_test
10 sys/tg_tes
9 sys/tg_te
8 sys/tg_t
7 sys/tg_
6 sys/tg
5 sys/t
4 sys/
3 sys
2 sy
1 s
0 
27 sys/tg_test/1/double_scalar
26 sys/tg_test/1/double_scala
25 sys/tg_test/1/double_scal
24 sys/tg_test/1/double_sca
terminate called after throwing an instance of 'Tango::DevFailed'
Aborted
```

**Comment by cpascual** [comment]
... And with an even simpler snippet:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.container import TaurusWidget

app = TaurusApplication(cmd_line_parser=None)
w = TaurusWidget()
w.show()

def loopmodels():
    for i in range(1000):
        w.setModel('a/b/c/{}'.format(i%2))
        app.processEvents()

loopmodels()
```

```console
$ python3 stress3.py 
MainThread     INFO     2019-07-25 16:37:02,159 TaurusRootLogger: Using PyQt5 (v5.6 with Qt 5.6.2 and Python 3.6.8)
MainThread     INFO     2019-07-25 16:37:02,424 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /nfs/home/cpascual/src/taurus/lib/taurus/qt/qtgui/icon/)
MainThread     INFO     2019-07-25 16:37:02,684 TaurusRootLogger: Plugin "taurus_pyqtgraph" loaded as "taurus.qt.qtgui.tpg"
TimerLoop 1    WARNING  2019-07-25 16:37:06,283 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    WARNING  2019-07-25 16:37:10,512 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    WARNING  2019-07-25 16:37:14,606 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
Exception in thread TimerLoop 1:
Traceback (most recent call last):
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/cpascual/miniconda/envs/py3qt5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/util/timer.py", line 91, in __run
    self.__function(*self.__args, **self.__kwargs)
  File "/nfs/home/cpascual/src/taurus/lib/taurus/core/tauruspollingtimer.py", line 136, in _pollAttributes
    for dev, attrs in self.dev_dict.items():
RuntimeError: dictionary changed size during iteration

TimerLoop 1    ERROR    2019-07-25 16:37:14,994 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    ERROR    2019-07-25 16:37:15,018 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:18,271 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:18,272 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:21,626 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:21,627 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:24,981 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    WARNING  2019-07-25 16:37:28,800 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:28,801 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    ERROR    2019-07-25 16:37:29,011 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    ERROR    2019-07-25 16:37:30,018 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:33,336 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:33,337 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:36,716 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:36,717 TaurusPollingTimer[3000]: poll_reply error
TimerLoop 1    WARNING  2019-07-25 16:37:40,154 TaurusPollingTimer[3000].Timer on _pollAttributes: loop function took more than loop interval (3.0s)
TimerLoop 1    ERROR    2019-07-25 16:37:45,016 TaurusPollingTimer[3000]: poll_reply error

```

**Comment by cpascual** [comment]
I think this is a corner case and not release-critical, so moved it to Jan20 milestone
