### ISSUE TITLE
taurus gui example01 (win py3qt5): zero division error when resizing trend

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#970]
When performing manual tests for release Jul19, on win10 vm, with conda environment py3qt5:

taurus gui example01 (win py3qt5): zero division error when resizing trend

Error in prompt when resizing the trend to a small size. 
How to reproduce: by making really small (resizing) the widget of the taurus_tpg_trend inside the main GUI of example01

<pre>
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 525, in paint
    specs = self.generateDrawSpecs(painter)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 819, in generateDrawSpecs
    tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus_pyqtgraph\dateaxisitem.py", line 145, in tickValues
    majticks = majticks[::int(numpy.ceil(float(L) / maxMajSteps))]
ZeroDivisionError: float division by zero
</pre>

**Comment by cpascual** [comment]
Fixed in taurus_pyqtgraph 0.2.4a
