### ISSUE TITLE
taurus demo: Led 

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#972]
When performing manual tests for release Jul19, on win10 vm, with conda environment py3qt5:

Execute:
```
taurus demo
```
'Led' button demo

Modifying model names:

Remove the attribute '/state' from the model name 'sys/tg_test/1/state'; in such a way to only leave the device name 'sys/tg_test/1' (Maybe, it is not 100% reproducible).

Error Traceback:
<pre>
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\base\taurusbase.py", line 394, in filterEvent
    self.handleEvent(*evt)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\display\taurusled.py", line 267, in handleEvent
    self.controller().handleEvent(evt_src, evt_type, evt_value)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\display\taurusled.py", line 255, in controller
    ctrl_klass = self._calculate_controller_class()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\display\taurusled.py", line 242, in _calculate_controller_class
    elif model.isBoolean():
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\tangodevice.py", line 79, in __getattr__
    return getattr(self._deviceObj, name)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\tango\device_proxy.py", line 319, in __DeviceProxy__getattr
    raise AttributeError(name)
AttributeError: isBoolean
</pre>

**Comment by cpascual** [comment]
I can reproduce it with debian py3qt5

**Comment by cpascual** [comment]
It can be reproduced with:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLed

if __name__ == '__main__':
    import sys
    app = TaurusApplication(cmd_line_parser=None)

    w = TaurusLed()

    model = 'sys/tg_test/1'
    w.setModel(model)

    w.show()
    sys.exit(app.exec_())
```

**Comment by cpascual** [comment]
...but this is actually not a bug... TaurusLed expects an attribute as its model, and here we are giving it a device.
