### ISSUE TITLE
Win10 py3qt5 Taurus 4.6.0: some automatic tests fails

### ISSUE THREAD

**Issue by mrosanes** [taurus-org/taurus#976]
Win10 py3qt5 Taurus 4.6.0: some automatic tests fails

See output of automatic tests on:
https://gist.github.com/mrosanes/5a4cafb3d5c4458ab1e54453f3714bda

**Comment by mrosanes** [comment]
Error / Failing automatic tests on Windows are the following:

======================================================================
ERROR: taurus.core.epics (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: taurus.core.epics
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\unittest\loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "c:\miniconda\envs\py3qt5\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\epics\__init__.py", line 70, in <module>
    from .epicsfactory import *
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\epics\epicsfactory.py", line 31, in <module>
    import epics
ModuleNotFoundError: No module named 'epics'


======================================================================
ERROR: test_read_attr (taurus.core.evaluation.test.test_evalattribute.EvalAttributeTestCase)
Testing read_attr(attr_fullname='eval:@os.*/path.exists("c:\\miniconda\\envs\\py3qt5\\lib\\site-packages\\taurus\\core\\evaluation\\test\\test_evalattribute.py")', expected={'rvalue': True, 'type': 3, 'label': 'path.exists("c:\\miniconda\\envs\\py3qt5\\lib\\site-packages\\taurus\\core\\evaluation\\test\\test_evalattribute.py")', 'writable': False}, expected_attrv={'rvalue': True, 'wvalue': None}, expectedshape=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\base.py", line 113, in newTest
    return helper(**helper_kwargs)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\evaluation\test\test_evalattribute.py", line 272, in read_attr
    a = taurus.Attribute(attr_fullname)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\taurushelper.py", line 315, in Attribute
    return Factory(scheme=getSchemeFromName(dev_or_attr_name)).getAttribute(dev_or_attr_name)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\evaluation\evalfactory.py", line 200, in getAttribute
    a = EvaluationAttribute(fullname, parent=dev, **kwargs)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\evaluation\evalattribute.py", line 186, in __init__
    trstring = self._validator.getExpandedExpr(str(name))
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\evaluation\evalvalidator.py", line 489, in getExpandedExpr
    return self.expandExpr(_expr, _subst or {})
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\evaluation\evalvalidator.py", line 264, in expandExpr
    ret = re.sub(s, placeholder, ret)
  File "c:\miniconda\envs\py3qt5\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\miniconda\envs\py3qt5\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\miniconda\envs\py3qt5\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "c:\miniconda\envs\py3qt5\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "c:\miniconda\envs\py3qt5\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "c:\miniconda\envs\py3qt5\lib\sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "c:\miniconda\envs\py3qt5\lib\sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \m at position 3

======================================================================
ERROR: setUpClass (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\test\tgtestds.py", line 56, in setUpClass
    cls._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: setUpClass (taurus.core.tango.test.test_tangofactory.TestFactoryGarbageCollection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\test\tgtestds.py", line 56, in setUpClass
    cls._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: setUpClass (taurus.qt.qtgui.base.test.test_taurusbase.GetDisplayValueTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\test\tgtestds.py", line 56, in setUpClass
    cls._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: testTimeOutError (taurus.qt.qtgui.button.test.test_taurusbutton.TaurusCommandButtonTest2)
Check that the timeout property works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\qt\qtgui\button\test\test_taurusbutton.py", line 76, in setUp
    self._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: setUpClass (taurus.qt.qtgui.display.test.test_tauruslabel.TaurusLabelTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\test\tgtestds.py", line 56, in setUpClass
    cls._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: setUpClass (taurus.qt.qtgui.panel.test.test_taurusvalue.TaurusValueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\test\tgtestds.py", line 56, in setUpClass
    cls._starter.startDs()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 107, in startDs
    self.start()
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\tango\starter.py", line 216, in start
    self.process = subprocess.Popen(args, stdout=dev_null, stderr=dev_null)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\miniconda\envs\py3qt5\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

======================================================================
ERROR: testImportSubmodules (taurus.test.test_import.TaurusImportTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\test_import.py", line 67, in testImportSubmodules
    exclude_patterns=exclude_patterns)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\moduleexplorer.py", line 216, in explore
    minfo = explorer.exploreModule(modulename)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\moduleexplorer.py", line 130, in exploreModule
    self._getSubpackagesFromPath(modulepath)
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\moduleexplorer.py", line 74, in _getSubpackagesFromPath
    ret = [re.findall(r".+\/(.*)\/__init__.py", s)[0] for s in g]
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\test\moduleexplorer.py", line 74, in <listcomp>
    ret = [re.findall(r".+\/(.*)\/__init__.py", s)[0] for s in g]
IndexError: list index out of range

======================================================================
FAIL: test_calltimes (taurus.core.util.test.test_timer.TimerTest)
check the quality of the Timer's timing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\py3qt5\lib\site-packages\taurus\core\util\test\test_timer.py", line 78, in test_calltimes
    self.assertLess(drift, tol, msg)
AssertionError: 0.006544923782348611 not less than 0.001 : Too much drift (0.00654492). Tolerance=0.001

----------------------------------------------------------------------
Ran 506 tests in 254.593s

FAILED (failures=1, errors=9, skipped=1)
Assertion failed: Successful WSASTARTUP not yet performed (..\..\..\src\signaler.cpp:377)
