### ISSUE TITLE
Taurus form RuntimeError

### ISSUE THREAD

**Issue by amilan** [taurus-org/taurus#980]
Running a taurus form with the following command:
```
taurus form sys/tg_test/1/short_scalar
```
And after doing: right click -> Configuration -> All, and closing the appearing Dialog, I've got the following error in a continuous way:

```
Traceback (most recent call last):
  File "/projects/lib-cells-taurus/lib/taurus/qt/qtgui/base/taurusbase.py", line 394, in filterEvent
    self.handleEvent(*evt)
  File "/projects/lib-cells-taurus/lib/taurus/qt/qtgui/panel/taurusconfigurationpanel.py", line 61, in handleEvent

    self.notifyValueChanged()
  File "/projects/lib-cells-taurus/lib/taurus/qt/qtgui/panel/taurusconfigurationpanel.py", line 124, in notifyValueChanged
    if str(self.text()) != str(self.getValue()):
RuntimeError: wrapped C/C++ object of type TangoConfigLineEdit has been deleted
``` 

I'm doing this test with CentOS7, python 2.7 and PyQT4.

**Comment by cpascual** [comment]
Hi @amilan, I cannot reproduce it with debian9 py2qt4 , debian9 py3qt5 or debian10 py3qt5

So, just to try to understand:
- Is this 100% reproducible in your platform?
- how do you close the dialog?
- how did you install your pyqt and tango (and which versions?)

**Comment by amilan** [comment]
> Is this 100% reproducible in your platform?

100% reproducible even with taurus 4.5.1 (previous release)

> how do you close the dialog?

Closing the dialog with the OK button is enough to produce the issue.

> how did you install your pyqt and tango (and which versions?)

PyQt4 and Tango are installed via RPM package. The one for PyQt4 is the one provided by the CentOS base repository, the Tango and PyTango RPMs are the ones provided by the maxiv repository.

Versions:
- CentOS 7
- Tango: 9.3.2 and 9.3.3
- PyTango: 9.3.0
- PyQt4: 4.10.1
